### ISSUE TITLE
Add a clause for the OGC API Guidelines checklist.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#101]
See https://github.com/opengeospatial/OGC-Web-API-Guidelines/tree/V1.0
We should add a section to the specification  that has an OGC API checklist and make sure that Records ticks as many boxes as possible.

**Comment by cportele** [comment]
I would recommend to simply document this in a separate markdown page in the repo, but keep this out of the standard. It is not relevant information for using the standard, it is mainly to inform the OAB or the OGC membership during the development process.

**Comment by pvretano** [comment]
@cportele sure.  Just figured the OAB, when we get there, will want a checklist.  A separate document is fine.

**Comment by tomkralidis** [comment]
first pass/PR in #107

**Comment by pvretano** [comment]
21-APR-2023: Close by PR #107.
