### ISSUE TITLE
sortby regex

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-records#102]
The current regex of the `sortby` parameter is `[+-]?[A-Za-z_][A-Za-z0-9]*`. 

Isn't `[A-Za-z0-9]*` too strict? This is a very strict constraint on the names of sortables. In general we have avoided such constraints in the standards (server implementations are free to support only a restricted subset, of course). 

This is also relevant for STAC compatibility (use of "." or ":" in property names), I think.

**Comment by pvretano** [comment]
@cportele I agree.  I have a rewritten one that I have not pushed to the repo yet.  Next push should update it.

**Comment by pvretano** [comment]
Changed sortby regex to be: [+-]?[A-Za-z_].*
