### ISSUE TITLE
Make it clear that metadata about models are supported too

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-records#104]
We need to make it clear that metadata about models are supported too. That is, we need to list 'models' alongside other resources that can be recorded.

Please update the following pages to reflect support for models:

- [Abstract](https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/clause_0_front_material.adoc)
- [Scope](https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/clause_1_scope.adoc)

This is relevant to machine learning, modeling, simulation & gaming.

**Comment by pvretano** [comment]
08-MAR-2021: Sure, we can add informative text to indicate that models can also be resources that can be described in the cataloague.

**Comment by pvretano** [comment]
Scope has been updated to indicate that machine models are resources and can be registered and discovered using records in a catalogue.

**Comment by pvretano** [comment]
19-APR-2021: Added comments in the opening text that medata about models can be stored as records too.

**Comment by ghobona** [comment]
Some related Testbed activities:

* Testbed-16 Machine Learning ER (used OGC API - Records) https://docs.ogc.org/per/20-015r2.html
* Testbed-15 Machine Learning ER (used CSW) http://docs.opengeospatial.org/per/19-027r2.html
* Testbed-14 Machine Learning ER (used CSW) https://docs.ogc.org/per/18-038r2.html

**Comment by pvretano** [comment]
@ghobona ca we close this?

**Comment by ghobona** [comment]
@pvretano Yes, please close it.
