### ISSUE TITLE
Consistent naming of parameters and properties.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#108]
This issue is to highlight the fact that there is a bit of inconsistency with the naming of parameters and core properties in the specification.  For example we have the `recordid` property but then we also have the `record-created` and `record-updated` properties.  Also, there is the `externalid` query parameter but common requires lower-kebab-case for parameters so it should be `external-id`.  
Anyway, I want to try and sync all this up using the basic rule that is a parameter or a core queryables property is the concatenation of two words (e.g. sortby,contactPoint) then I will update it to be lower-kebab-case (i.e. sort-by, contact-point) unless we inherited the parameter/core property from somewhere else (e.g. datetime from features).

Does anyone have any issue with this approach?

**Comment by pvretano** [comment]
OK ... so based on this discussion https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby?at=605e1497559d0e099a60d8d3 and this issue https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/261#issuecomment-808359303 I think I will leave parameters as kebab-case (because of OGC API Common requirements) but change the schema properties to ??? ... the choices are snake_case or lowerCamelCase.  I prefer lowerCamelCase so I will go with that unless someone violently objects.
  
So just to summarise ...

1. Parameter names will follow OGC API Common and be lower-kebab-case OR will stay the same if we inherited the parameter from somewhere else (e.g. datetime).
2. Schema properties will be lowerCamelCase

**Comment by cportele** [comment]
One issue with that is the fact that some names will be used both as query parameters and as JSON keys. The current `externalid` is an example. See also https://github.com/opengeospatial/ogcapi-common/issues/224#issuecomment-808702183.

Also note that kebab case is not a requirement in Common, it is a recommendation.

**Comment by pvretano** [comment]
I'm not tied to one specific casing convention personally just as long as we are consistent and so since it seems that the issue is all over the place I think I will stick with lowerCamelCase everywhere unless we inherited the parameter/property from somewhere else (e.g. sortby) in which case we will stick with the inherited name.

Everyone ok with that?

**Comment by ghobona** [comment]
A similar conversation is taking place at https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/261

**Comment by pvretano** [comment]
OK.  One more time ... looking at https://github.com/opengeospatial/ogcapi-common/issues/224 ... I hope the following guding principles are sufficient:

1) query parameters are kebab-case
2) schema properties are lowerCamelCase
3) If a schema property is also a query parameter then both at lowerCamelCase
4) If the schema property or query parameter was inherited from somewhere else then we use the inherited form (e.g. sortby is inherited from STAC so sortby it shall be).

**Comment by rob-metalinkage** [comment]
To simplify the logic - here is the same set of principles restated in an order that allows simple parsing from the top, not look-ahead to find exceptions:
1. If the schema property or query parameter was inherited from somewhere else then we use the inherited form (e.g. sortby is inherited from STAC so sortby it shall be).
2. otherwise all schema properties are lowerCamelCase
3. If a query parameter is also a schema property, then use schema property naming as above
4. otherwise query parameters are kebab-case 

ps - I support lowerCamelCase as its the UML practice and also OWL - the two languages we use to define things. Many different schema languages can be used to encode conceptual things, and they may have specific rules.
 Query parameter syntax is just another schema - so this may require some thought about defining what a schema is in general.

**Comment by cnreediii** [comment]
So, hearing the term "kabob case" I did a bit of research :-) The above technical discussion aside, a summary of some of the issues of using kebob case. Perhaps not an issue if we are only staying with JSON but as a standards organization we should probably consider that other languages may or will be used - especially when a core of a standard is platform and language agnostic. 

1. The biggest problem with kebab case lies mainly on the use of a dash. Many programming languages will interpret the dash as a minus sign, and it unintentionally creates software bugs that are difficult to isolate and troubleshoot.

2. Similarly, many programming languages -- such as Jekyll -- will assume numbers separated by a dash are dates. This misinterpretation can cause problems when a developer uses kebab case with spreadsheets or calendar-based applications.

While kebab case can be useful, a developer must be aware that a dash can cause unintentional issues with non-letter codes.

**Comment by pvretano** [comment]
05-MAY-2021: There are three core queryables that are kebab-case, record-id, record-created, record-updated.  To avoid any issues with modules thinking these are arithmetic expressions (e.g. CQL) we will change these to be lowerCamelCase.

**Comment by pvretano** [comment]
21-APR-2023:  Closing.  The names of the record properties are now pretty well settled.  If further changes need to be made, these can be done on a per-occurrence basis using a new issue each time.
