### ISSUE TITLE
consider citation in record model

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#116]
As mentioned by @gaubert, it would be valuable to express citation in record metadata.  Should we consider this for the core (i.e. `properties.bibliographicCitation`) or leave for downstream communities to define as extensions/additional properties.

**Comment by pvretano** [comment]
@tomkralidis I know this is important for certain domains but I am not sure this is "core" functionality.  I would leave it for communities that want it to define.

**Comment by chris-little** [comment]
@pvretano I agree that it is important for some communities, and perhaps they should define the details, but I do not think that that would encourage interoperability. Maybe there needs to be a standard extension/part/framework to ensure reasonable interoperability with details such are style, language or terminology being communnity defined.

**Comment by m-mohr** [comment]
For what it's worth, here's the corresponding STAC extension for inspiration and/or alignment: https://github.com/stac-extensions/scientific

**Comment by tomkralidis** [comment]
SWG 2021-06-17: @cportele keep core as small as possible. Can be part of extension, or proposal for future work.

**Comment by pvretano** [comment]
07-APR-2023: Not applicable for core.
