### ISSUE TITLE
Consider the relationship between OGC API Records and the GeoVolumes SWG/specification ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#127]
The GeoVolumes work seems to be related to the work of this SWG.  We should probably review and comment.  Here are some resources:

Proposed charter: https://portal.ogc.org/files/?artifact_id=97171&version=3
ER: https://docs.ogc.org/per/20-030.html

**Comment by pvretano** [comment]
13-SEP-2021: Not much knowledge in the group about GeoVolumes so we will need to research a bit more before we can respond.

**Comment by pvretano** [comment]
04-OCT-2021: TC vote for the formation of the GeoVolumes SWG just finished.  We will leave this issue open for the time being until he get a better handle on what the relationship might be ... but this will not delay part 1 in any way.

**Comment by pvretano** [comment]
07-FEB-2022:  The latest version of the GeoVolumes spec is now available.  SWG member should review and see if there is any relationship to records or not.  I will provide a link to the specification shortly.

**Comment by cnreediii** [comment]
I scanned the version on GitHub (4 days old). No mention of Records in References, Scope, or normative clauses (requirements).

**Comment by pvretano** [comment]
07-MAR-2022: The relationship between GeoVolumes and OARec is the same as the relationship between Tiles and OARec which is to say that there may be might be some relationship (e.g. using GeoVolumes as an indexing structure or visa versa).  However, we don't see any standardization target here so we are closing.  Please feel free to reopen with additional comments if you thing there might be something for the SWG to consider.
