### ISSUE TITLE
verify the spec document on references to various xml models 

### ISSUE THREAD

**Issue by pvgenuchten** [opengeospatial/ogcapi-records#135]
3 model types of response xml for record requests can be differentiated:
- [open api xml](https://swagger.io/docs/specification/data-models/representing-xml) (following the structure of the openapi document)
- atom+xml (as used in OpenSearch)
- dedicated schema's such as Dublin Core, iso19115, ...

My impression is that http://docs.ogc.org/DRAFTS/20-004.html#_xml_encoding indicates option 3 from the above listing. In chapter 14 option 1 of the listing is not included. Has this case been considered?

Differentiation between these models can either run via a dedicated accept-header:
- application/vnd.iso19139+xml
- application/atom+xml
And/Or via conneg-by-profile

The standard should indicate which of above is returned when users request a basic xml encoding (such as text/xml), my suggestion would be in that case to return the xml structure defined by the openapi document.

**Comment by pvretano** [comment]
13-SEP-2021: Not sure what @pvgenuchten is requesting here so I (@pvretano) will circle back with him for clarification.  What response you get depends on the endpoint you are hitting what the negotiated output format.  There is also the intersectional issue of schema and output format. @pvretano will create an issue about this.

**Comment by pvgenuchten** [comment]
Sorry the question is not clear, let me make it more exact. What flavor of xml do we expect to return when hitting the endpoints /collections, /collections/foo, and collections/foo/items with a accept header of text/xml or application/xml? Or would it return unsupported because it expects application/atom+xml.

**Comment by pvretano** [comment]
04-OCT-2021: The core specification does not define the behaviour of the server when the negotiated format is text/xml or application/xml; the core is restricted to JSON.  This, of course, does not mean that a separate extension (e.g. a ISO19115) cannot use XML as the output formats.  There is no restriction in the specification about supporting other output formats.   It's just something that will not be specified in the core.  Although the current version of the specification includes OpenSearch and ATOM, we resolved a while back to move those bits into a separate extension.

**Comment by pvretano** [comment]
07-DEC-2021: A bit more information ... there is ongoing discussion about creating an ISO19115 extension for XML models are not being ignored.  They are just not part of Part 1 of the specification.  Both the OpenSearch and a potential ISO19115 extension would both use XML.

**Comment by pvretano** [comment]
07-MAR-2022: Since records is now using Features as its API and Features has XML responses defined for each endpoint the answer to the original question in this issue is look  here: **http://schemas.opengis.net/ogcapi/features/part1/1.0/xml/**.  The core.xml file has the response models for all the non-features resources (/,/conformance,/collections, etc.) and the core-sf.xml file has the response models that are feature specific.  Closing for now.  Reopen if more needs to be said.
