### ISSUE TITLE
consider qualification of externalId

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#137]
In the [core record model](https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml#L74-L80), `externalId` is defined as an array.  Should we consider qualifying lists of `externalId`'s to be able to delineate accordingly?  For example, for WMO station metadata, we have a number of identifiers (WIGOS ID, ICAO ID, etc.), i.e.:

```json
"externalId": [
    {
        "scheme": "WIS",
        "value": "urn:x-wmo:md:int.wmo.wis::ca.gc.ec.msc-1.1.1.1.10 "
    },
    {
        "scheme": "ICAO",
        "value": "foo123"
    }

]
```

**Comment by pvretano** [comment]
13-SEP-2021: @tomkralidis to make proposal for consideration

**Comment by tomkralidis** [comment]
Proposal in #142

**Comment by tomkralidis** [comment]
Update from SWG meeting 2021-11-15: agreed/consensus to merge, via #143
