### ISSUE TITLE
add version of record metadata

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#138]
We should consider supporting so clients can detect which version of a given record metadata they are handling.  This is especially useful in the case of the crawlable catalogue case (where a user wouldn't necessarily be able to detect conformance classes with an API per se).  Having said this, perhaps specifying conformance in the record?

**Comment by pvretano** [comment]
13-SEP-2021: Is the version monotonic increasing?  Yes. Do we need to handle profiles as well?  Probably. @tomkralidis to make a proposal.

**Comment by tomkralidis** [comment]
PR in #144

**Comment by tomkralidis** [comment]
Update from SWG meeting 2021-11-15: agreed/consensus to merge, via #144
