### ISSUE TITLE
filter by keyword from specific controlled vocabulary

### ISSUE THREAD

**Issue by pvgenuchten** [opengeospatial/ogcapi-records#139]
What is the best approach to allow filtering on keyword-from-vocabulary?

For example:
```
?vocabulary=NGDA%20Theme&keyword=Transportation
```
But this is problematic if the filter has 2 keywords from 2 vocabularies

An optimal approach would be to filter by keyword uri (which binds the keyword to a vocabulary)?

**Comment by pvretano** [comment]
@pvgenuchten that is what the `themes` queryable is for ... so, from the example in the specification ...

```
        "themes": [
            {
                "concepts": [
                    "dobson",
                    "brewer",
                    "vassey",
                    "pion",
                    "microtops",
                    "spectral",
                    "hoelper",
                    "saoz",
                    "filter"
                ],
                "scheme": "https://geo.woudc.org/codelists.xml#WOUDC_InstrumentCode"
            },
            {
                "concepts": [
                    "atmosphericComposition",
                    "pollution",
                    "observationPlatform",
                    "rocketSounding"
                ],
                "scheme": "https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode"
            }
        ],
```
You can then use a filter to say something like:
```
?scheme=https://geo.woudc.org/codelists.xml#WOUDC_InstrumentCode&term=spectral
```
Of course, you need to expose `scheme` and `term` as queryables from the `/queryables` endpoint.

Does that help?

**Comment by pvretano** [comment]
@pvgenuchten on second reading, I think this [clause](https://docs.ogc.org/DRAFTS/20-004.html#sc_keywords_and_themes) probably needs to be expanded a bit with more explanation.  The idea is that you can tag a record with free form keywords AND/OR you can also tag a record with terms/concepts/nodes from a formal taxonomy.
I think the example in the specification is great if you are a meteorologist but useless for everyone else.  We probably need an additional example using a much simpler and more relatable taxonomy based on `food` or `vehicles` or something like that.
I'll take a stab at an edit before the next meeting.

**Comment by pvretano** [comment]
07-APR-2023: Related to issue #181.
