### ISSUE TITLE
Review the FAIR principles and make sure we follow them in our work

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#14]
SWG Meeting 02-DEC-2019: The issue of the FAIR principles was raised in the SWG meeting today.  Since FAIR is referenced on OGC's main paid we should review the principles and make sure that we follow them.

**Comment by jyutzler** [comment]
For the uninitiated, LMGTFY led me to https://www.go-fair.org/fair-principles/.

**Comment by jyutzler** [comment]
Opened with the OAB as issue 1444.
