### ISSUE TITLE
consider temporal resolution

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#147]
For metadata records which are not split temporally by some resolution, should we consider temporal resolution (a la `dcat:temporalResolution`)?  Imagine for data which updates daily/hourly/etc.:

```json
                "temporal": {
                    "interval": [
                        [
                            "2000-10-30T18:24:39+00:00",
                            "2007-10-30T08:57:29+00:00"
                        ]
                    ],
                    "resolution": "P1D"
                }
```

**Comment by pvretano** [comment]
04-OCT-2021: @tomkralidis to write up a PR to consider.

**Comment by tomkralidis** [comment]
PR in #149

**Comment by tomkralidis** [comment]
Update from SWG meeting 2021-11-15: agreed/consensus to merge (done via #149)
