### ISSUE TITLE
Review and comment on outline.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#15]
SWG Meeting 02-DEC-2019: It was decided today that in order to kickstart the work of the SWG, participants should review and comment on the [outline](https://github.com/opengeospatial/CAT4.0/blob/master/core/outline.adoc).  Issues or pull requests may be used.  As we review and deal with each issue/pull request we can review the outline until it forms a good basis for the first draft of the core document.

**Comment by cportele** [comment]
SWG Meeting 16-DEC-2019: Please try to get review comments in by end of January 2020.

**Comment by cportele** [comment]
We close this issue and wait for the OGC-API-Common-based draft document, which should be ready soon, and then start reviewing that draft.
