### ISSUE TITLE
ISO19115-3 mappings to OARec

### ISSUE THREAD

**Issue by ByronCinNZ** [opengeospatial/ogcapi-records#152]
Candidate crosswalk attached. Needs discussion.
[iso19115OARec-Crosswalk.xlsx](https://github.com/opengeospatial/ogcapi-code-sprint-2021-07/files/6862556/iso19115OARec-Crosswalk.xlsx)
Note - This is a crosswalk for the latest version of ISO19115-3 based on ISO19115-1:2018. There will be some differences to 19139 metadata based on ISO19115:2004

**Comment by pvretano** [comment]
07-APR-2023: Looks like a duplicate of #174.  Work can continue in the more recent issue.
