### ISSUE TITLE
Sortable support for allowing sorting over fields not explicitly mentioned in /sortables

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-records#153]
The Queryables mechanism in CQL support uses a field `additionalProperties` to indicate that the server allows values to be requested that are not explicitly defined as queryables. This should also be applied to the Sortable specification, so a client may request sorting on a property that may not exist on any or all of the result entities and is not explicitly defined as a sortable field in the `.../sortables` endpoints.

**Comment by pvretano** [comment]
29-NOV-2021: The SWG agree with @philvarner and as mentioned, the sortables are derived from the queryables stuff so additionaProperty=true is already there.  A related issues #126 mentions that we are moving the API stuff of records (q, sortables, etc.) to features.
