### ISSUE TITLE
review responsibleParty.yaml

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#155]
Given some references to ISO 19115:2003, suggest a review of https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/responsibleParty.yaml against the latest ISO 19115 standard cc @ByronCinNZ

**Comment by tomkralidis** [comment]
https://github.com/ISO-TC211/XML/tree/master/standards.iso.org/iso/19115/-3/cit/2.0

**Comment by pvretano** [comment]
29-NOV-2021: General feeling is that the ISO structure is really heavy!  What we should do is make sure that our responsible part structure is a pared down subset of the ISO one so that ours can be extended to be the ISO structure. @tomkralidis will do the crosswalk between what we have now and the ISO structure to make sure that nothing critical is missing and also to make sure ours is much lighter than the ISO structure.

**Comment by tomkralidis** [comment]
A review of the ISO 19115-3 structure for citation yields the following notes:
- entities are now called `CI_Party` (departing from CI_ResponsibleParty`), which can be an individual or organization
- gone are `individualName` and `organizationName` in lieu of `name` (a la STAC [providers](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object)
  - if the party is an individual, then a `positionName` is available for use
  - if the party is an organization, then
    - an `individual` element is available for use (using the same `CI_Party` model) to further identify an actual individual within an organization
    - a `logo` element is available so as to display a graphic/image
- we now see a `partyIdentifier` attribute ("value uniquely identifying a party").  This is valuable for acronyms

Given the above, as well as the comments in #154 RE: STAC alignment, a PR will be put forth for review/comment.

**Comment by tomkralidis** [comment]
PR in #156

**Comment by tomkralidis** [comment]
Update from SWG meeting 2021-12-07:
- crosswalk role from both ISO 19115 and the STAC collection `provider.role`
- update or remove references to 19115:2003

**Comment by tomkralidis** [comment]
- STAC provider roles: https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object
  - licensor
  - producer
  - processor
  - host
- ISO role codes: https://schemas.isotc211.org/schemas/Resources/codelists.xml
  - resourceProvider
  - custodian
  - owner
  - user
  - distributor
  - originator
  - pointOfContact
  - principalInvestigator
  - processor
  - publisher
  - author
  - sponsor
  - coAuthor
  - collaborator
  - editor
  - mediator
  - rightsHolder
  - contributor
  - funder
  - stakeholder

**Comment by tomkralidis** [comment]
Implemented in #156
