### ISSUE TITLE
Subtle differences in property naming between DCAT and Records

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#158]
At the SWG meeting at the DEC2021 members meeting there was an observation that the names of RECORD properties that correspond to DCAT are in some cases slightly different (e.g. plural instead of singular, etc.).  We should crosswalk the RECORD property names with the DCAT property names and make sure that the ones that coincide are the same ... or at least explain why they are slightly different.

**Comment by pvretano** [comment]
07-MAR-2022: In order to try and resolve the tension between OAPIR, DCAT and STAC property names it was proposed in today's SWG teleconference that we include the above crosswalk table in the specification.  Then, as much as possible align the OAPIR key named with DCAT  and extend the table to include STAC names and say that those names can also be used as aliases.  This way client can be prepared to see with the OAPIR/DCAT key names or their STAC equivalent.  We will give this a try and see how it flies.

**Comment by kalxas** [comment]
Do we perhaps need a separate issue just for folding associations into links?

**Comment by tomkralidis** [comment]
+1, support/makes sense.

**Comment by ycespb** [comment]
About the duplicate keys such as "created" etc...  A JSON solution aligned with DCAT/GeoDCAT-AP, avoiding to have to invent new key names  is to use the following encoding where the metadata information goes in $.properties.isPrimaryTopicOf.

- $.properties.isPrimaryTopicOf.created  (metadata property)
- $.properties.created  (resource property)

See https://docs.ogc.org/bp/17-084r1/17-084r1.html#toc27 and Figure 1 in the DCAT spec  https://www.w3.org/TR/vocab-dcat-2/#dcat-scope which shows the foaf:primaryTopic relation between dcat:CatalogRecord and dcat:Resource.  IsPrimarytopicOf is the inverse relation  of primaryTopic.

**Comment by m-mohr** [comment]
After solving #178, some additional notes:
- stac_extensions has the same purpose as conformsTo basically. Still, they can be separate, no issues expected.
- I heard today that records may also have a field for temporal information, but I don't see it captured here.
- `type` is listed twice in the table?
- keywords will likely also be present in STAC: https://github.com/radiantearth/stac-spec/issues/1187
- for keywordsCodespaces, I think there's a proposal for a subjects extension: https://github.com/stac-extensions/subjects
- language: I'll propose to use the same term in STAC: https://github.com/radiantearth/stac-api-spec/issues/306
- How close is the content of license and providers aligned in STAC and Records?
- What is the extent useful for if you already have bbox and potentially the time property from JSON-FG?

**Comment by pvretano** [comment]
@m-mohr about one type ... one "type" is for the record and the other "type" is for the link ... actually href, rel, type and title are all meant to be fields of the link.  My table needs a bit of restructuring! ;)

**Comment by m-mohr** [comment]
Oh, no, I actually meant the types at the beginning (so not in links/assets/...) of the list, but I now see that the one is in properties. Nevermind.

I've just also found themes instead of keywordNamespaces, which seems to be the equivalent to the subjects STAC extension proposal. I'll try to convince people to use themes, too.

**Comment by pvretano** [comment]
@m-mohr hold off on the convincing until after the code sprint.  keywords and themes are meant to do similar things.  The biggest difference is that keywords are a "free-form" list of keywords, whereas themes are from a formal vocabulary or thesaurus or classification scheme.

**Comment by m-mohr** [comment]
Yes, we have the same distinction and will definitively keep "keywords" as free-form ones / tags. And I think we are happy to adopt anything that you define for vocabulary-defined keywords in addition. For now I'm just trying to convince to align with Records, whatever that might be. (Although it might be that they want to define it "asap" and not just in a year ;-) )

**Comment by pvretano** [comment]
07-APR-2023: 
1. The schema of records has been set for quite some time now and has been harmonized with DCAT to the extent possible taking into account all the other conflicting interests.
2. There is a `conformsTo` tag in records that allow additional GeoDCAT members to be added to a record.
3. There is now a GeoDCAT SWG forming/formed in OGC that will handle all GeoDCAT issues.

**Comment by rob-metalinkage** [comment]
There is a formalism of this mapping using JSON-LD in this activity:  https://ogcincubator.github.io/geodcat-ogcapi-records/ 

This is part of the development and testing methodology of GeoDCAT (not to be confused with, but intended to the "common" - no EC centric - part of GeoDCAT-AP).

As part of the testing process, STAC/Records compatibility has been tested - and GeoDCAT profiles matching STAC extensions are being described.
