### ISSUE TITLE
Conneg by Profile

### ISSUE THREAD

**Issue by ByronCinNZ** [opengeospatial/ogcapi-records#16]
Explore the possibility of including the Content Negotiation by Profile being developed by the W3C Data Exchange Working Group - Rob Atkinson a good point person - https://www.w3.org/TR/dx-prof-conneg/

**Comment by jyutzler** [comment]
We're going to move this over to ogcapi-common.

**Comment by pvgenuchten** [comment]
Is there a link to where this is picked up in ogcapi-common

In https://github.com/opengeospatial/oapi_common/issues/116 and https://github.com/opengeospatial/oapi_common/issues/8 @cportele suggests to use content negotiation by iana types, this can work when using types such as application/iso19139+xml,  application/vnd.dcat.rdf+xml,  application/vnd.dcat.ld.json, but it is less flexible then prof-conneg

this topic is quite relevant in the scope of metadata records (crosswalks between dc-iso-dcat-datacite-schema.org-...)
I'd suggest to reopen if not picked up by common.
