### ISSUE TITLE
Questions about the current thinking of how more advanced spatial queries will be expresses in the API

### ISSUE THREAD

**Issue by gardengeek99** [opengeospatial/ogcapi-records#161]
I can see how simple spatial queries for searching records is expressed in the API using bbox=..... as part of a query string to a get request on a catalog collection.

Beyond that, I see references to CQL for doing more advanced query by more complex geometry using enhanced spatial operators like within, overlaps, etc... using query parameters like filter=INTERSECTS(geometry,POLYGON((1379213.867288 3610774.164192,1379233.837424 3610769.696029,1379246.149564 3610812.389132,1379226.494235 3610816.884823,1379213.867288 3610774.164192)))

Is this the correct interpretation of how that will be handled (given the current thinking of a specification in progress)?

**Comment by pvretano** [comment]
07-MAR-2022: Yes, that is the correct interpretation.  Records is using Features as it API and that is how it works in Features.  That is use can use bbox, datetile, property filtering if you have simple filtering requirements; more complex requirements are covered with CQL2 and Part3 of Features.  @gardengeek99 please review and close if you are satisfied with the answer here.
