### ISSUE TITLE
Anticipated Part 1 timeline

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#162]
The following is the anticipated timeline for Part 1 of OGC API - Records.  The most important thing is to leave time for implementations, testing, code sprints, etc. to shake down the specification.

- Mid/Late Q1 2022
    - initial, tagged, 1.0-draft
- Mid/Late Q1 to Mid Q3
    - Solicit feedback on 1.0-draft
    - Ongoing review of document and addressing of issues and comments
    - Implementations, implementations, implementation
    - Several implementations of searchable catalogues already exist
    - Code sprint(s)
    - Don’t want to rush this phase
- Mid Q3
   - Submission of OAB and 30-day RFC
   - Address RFC comments
- Late Q3 & Early Q4 
   - Submission to TC for adoption vote 
   - Thereafter we can consider an ISO submission.

**Comment by pvretano** [comment]
21-APR-2023: If we can complete the harmonization issues with STAC, and complete the ATS and clean up a few other minor editorial issues, we should be in a position to hand off the specification for OAB review by end of Sept.  Of course, we have other dependencies (e.g. Feature taking over the API components -- sorting, q, etc.) but from our end, end of Sept. seems achievable.

**Comment by kalxas** [comment]
We should submit to OAB once this one is completed: https://github.com/opengeospatial/ogcapi-records/issues/309

**Comment by pvretano** [comment]
@kalxas, once we finish #309  we can create a "1.0 DRAFT" tag but we still need to review the document and make sure everything is ship shape before we apporach the OAB.  Based on the project board I think we should be able to present to the OAB in Jan.

B.T.W. does anyone know the process for tagging a 1.0 Draft?

**Comment by kalxas** [comment]
We should also make sure that the ATS is updated every time we make changes to requirements.

**Comment by pvretano** [comment]
Since we are presenting to the OAB today, 14-MAY-2024, I'm closing this.  We were only off by a year! LOL!
