### ISSUE TITLE
Minting URLs with format and schema information

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#165]
CSW has the parameters outputFormat and outputSchema for negotiating what exactly the server generates.  The question at hand is how translate this into OGC API Records.  Perhaps f= and s=?  

So, unlike features, records need to negotiate both the format and the schema of the output.  For the format negotiation we can reference features.  For the schema negotiation, we will need to add something to the standard.

We should probably base the standard on work already does in this area.  Specifically take a looks at content negotiation by profile.

See profile link relation type: https://datatracker.ietf.org/doc/html/rfc6906
See content negotiation by profile too: https://www.w3.org/TR/dx-prof-conneg/ and https://datatracker.ietf.org/doc/html/draft-svensson-profiled-representations-01
NOTE: the w3c version is more complex than the ieft version which was already too complex for the ietf folks!
See also in common: https://github.com/opengeospatial/ogcapi-common/issues/8
See also in features: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#encodings

The goal here is to provide guidance on negotiating output format to a specific media type and schema AND for minting URLs that get embedded in other places.

**Comment by NuriaJulia** [comment]
What about links if we have a crawlable catalogue? Now, there is only the type and you cannot know what profile or standard or schema it follows! Can we add a "schema" or "profile" element?

**Comment by pvgenuchten** [comment]
See also #135 

I expect ?f=xxx&s=yyy as an override of accept:text/xml / accept:application/vnd.iso.19139
