### ISSUE TITLE
keywordsCodespace vs theme scheme

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogcapi-records#172]
In [Table 12](http://docs.ogc.org/DRAFTS/20-004.html#core-queryables-resource-table) a property `keywordsCodespace` is listed, but in the example in [7.2.3](http://docs.ogc.org/DRAFTS/20-004.html#sc_keywords_and_themes) it is stated that `keywords` is for free-form tags, while `theme` is meant to articulate terms from formal vocabularies. 

In [issue 70](https://github.com/opengeospatial/ogcapi-records/issues/70) there seems to be a documented decision to remove `keywordsCodespace`. Perhaps this has been left in by mistake?

**Comment by pvretano** [comment]
@lvdbrink I removed all references to keywordsCodespace ... I hope! ;)

**Comment by pvretano** [comment]
08-AUG-2022 SWG Meeting:  Leaving open till next meeting for people to review changes.

**Comment by lvdbrink** [comment]
Yep, all removed as far as I can tell!

**Comment by pvretano** [comment]
Closing since no additional comments have been added to the issue.
