### ISSUE TITLE
recordJSONFG schema missing?

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogcapi-records#176]
In **Requirement 93 | /req/jsonfg/content** under C, there is reference to a schema `recordJSONFG.yaml`. 

But directly below, the included and displayed schema is not a JSON-FG schema, but a GeoJSON schema (the same as referenced in the GeoJSON requirements class directly before). 

There is no schema `recordJSONFG.yaml` that I could find in this github repository and am not sure of the intent here. 

If the intent is to include a JSON-FG schema here, then it needs to be added and the schema inclusion link should be corrected. 

If the intent is to use the same GeoJSON schema here as in the GeoJSON requirements class, then the text in requirement 93 C should be corrected.

**Comment by pvretano** [comment]
@lvdbrink just a place holder for now.  If we decide to keep the JSON-FG conformance class then we can fill out the schema for a JSON-FG encoded record.

**Comment by pvretano** [comment]
08-AUG-2022 SWG Meeting: We will leave the current content in the document until after the upcoming code sprint.  At the code srpint we will have the opportunity to explore JSON-FG and Records since both are topics of the code sprint.

**Comment by cportele** [comment]
I had a look at the current text of the [JSON-FG requirements class](https://docs.ogc.org/DRAFTS/20-004.html#requirements-class-jsonfg-clause). Some questions:

* What should be the content of the JSON-FG "time" member? Is that up to the provider / the nature of the resource or should there be guidance based on the created/updated information about the record or its distributions?
* Should the "type" property be mapped to the JSON-FG "featureType" member?

In addition, see https://github.com/opengeospatial/ogc-feat-geo-json/issues/56.

**Comment by pvretano** [comment]
I would say that the "time" value is up to the provider / the nature of the resource ... not the created/update dates of the record itself.
About "featureType" ... yes I think the type should be mapped to the "featureType" member.

**Comment by cportele** [comment]
OGC Code Sprint 2022-09-15:

* Returning records in a CRS that is not WGS84 lon/lat is not an important use case for a Record API.
* Records specifies an application schema with standardized record properties, just like STAC. The same argument as stated in https://github.com/opengeospatial/ogc-feat-geo-json/issues/69#issuecomment-1248132912 applies for Records as well. We will therefore remove the JSON-FG requirements class from the current Records draft and include "time" and "type" in the "properties" member for now. If communities would start to use JSON-FG with record data we could revisit this in the future.

**Comment by pvretano** [comment]
14-NOV-2022: From the code sprint decided that at this time there is no value in using JSON-FG as a record encoding.  @pvretano will remove all reference to JSON-FG as a record encoding and close out the issue.

**Comment by pvretano** [comment]
This has been done via PR #210.  Closing this issue.
