### ISSUE TITLE
Making a searchable catalogue accessible by crawlable clients...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#180]
Right now, the crawlable catalogue conformance class has a bunch of links using root, parent and child rels for hooking up collections and records into a hierarchy.  Some examples:

https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/recommendations/crawlable-catalogue/REC_collections-links.adoc

https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/requirements/crawlable-catalogue/REQ_collections-links.adoc

The searchable coformance class, however, does not include those requirements since the hierarchy is set by the Feature speicification.  However, a searchable catalogue could include those links to make it accessible by crawlable clients so we should probably revist those "crawlable" requirements/recoomendations and apply them to "searchable" catalogue too.  It would just mean links point to similar stuff living side-by-side in the links section.

**Comment by m-mohr** [comment]
One issue that was raised by @cportele today: It seems OGC doesn't allow parent/child/root as rel type as it is not IANA registered. So if we want this to be aligned between STAC and Records (which it should be!), then we need to go through this inconvenience.

**Comment by cportele** [comment]
For additional background:

The OGC API standards now mostly register their link relation types in a link relation type register managed by the OGC Naming Authority. Each link relation type has a URI, that is used as the link relation type in accordance with RFC 8288. There is also a policy to allow the use of a CURIE, see [here](https://github.com/opengeospatial/NamingAuthority/blob/master/policyAndProcedures/OGCNANameTypeSpecificationForDefinitions/sections/06-naming-rule.adoc#compact-uris).

Registering generic link relation types (like root or parent) without a RFC or W3C Recommendation might be difficult. We tried to register link relation types from Features Part 1 like "conformance" or "data" with IANA, but that was rejected for these reasons - which I can understand. 

See also https://github.com/opengeospatial/ogcapi-common/issues/76.

**Comment by pvretano** [comment]
14-NOV-2022: @kalxas raised the issue that if there are millions of records in a searchable catalogue then linking them up in a "crawlable" fashion would result in million of links in the system which would make it unmanageable.  The way STAC handles this is to have collections of collections but this concept does not exist the features API.  This raises the question whether every searchable catalogue should be crawlable too.  Perhaps not wanted in all cases.

This is probably would be a good topic for a code sprint if there are client and server developers willing to implement the necessary nestable-collections idea.  Also a question ... does the STAC API handle this and if so how?  ... since it uses the Feature API and the concept of nested collection is not built into that API.

**Comment by pvretano** [comment]
12-DEC-2022: @pvretano will add an informative discussion is the specification basically stating that nested collections is not a concept that is currently part of OGC APIs.  However, if the need arrises, expressing a hierarchy can be done in records by creating a record describing each collection and then linking the records apporpriately.  Not ideal but will at least provide some guidance in this area.  If, in the future, OGC comes up with a nexted or hierarchical collection structure, we can adopt that in the OGC API Records.

**Comment by pvretano** [comment]
07-APR-2023: @pvretano still needs to add the informative discussion about how a searchable catalogue can be made accessible to a crawlable client.
