### ISSUE TITLE
specifying result elements

### ISSUE THREAD

**Issue by mhogeweg** [opengeospatial/ogcapi-records#184]
Is there an equivalent of the ElementSetName from CSW 2.x for OGC Records? along the lines of queryables there could be a resources for 'returnables' that lists different element sets that an application could request.

**Comment by pvretano** [comment]
@mhogeweg records will rely of a features extension to handle that.  See https://github.com/opengeospatial/ogcapi-features/tree/master/proposals/schemas to handle that.
