### ISSUE TITLE
update party definition

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#187]
https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/party.yaml allows the ability to specify a contact by reference (URL) or inline.  In the inline case, the `roles` array is allowed, however this is not available when specifying by reference/URL.

Any objections to updating the provider model to include `roles` as an optional property for either scenario?

**Comment by tomkralidis** [comment]
Example:

```json
"providers": [{
  "link": {
    "href": "https://example.org/contact"
  },
  "roles": ["distributor"]
}]
```

**Comment by pvretano** [comment]
28-NOV-2022: @tomkralidis SWG is agreement with the change.  Go ahead and create a PR for review at the next SWG meeting.

**Comment by tomkralidis** [comment]
PR in #192

**Comment by pvretano** [comment]
12-DEC-2022: Closing at PR #192 was merged.
