### ISSUE TITLE
clarify time vs. properties.created/properties.updated

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#189]
Table 10 defines `time` / `properties.created` / `properties.updated` as follows:

Queryable | Requirement | Description | GeoJSON key
-- | -- | -- | --
time | required | The temporal extent of the resource. Can be null. | `time`
created | optional | The date the resource was created. | `properties.created`
updated | optional | The more recent date on which the resource was changed. | `properties.updated`

What would be the difference?  I would `time` being closer to supporting temporal searching.

**Comment by kalxas** [comment]
I think this roots back to DublinCore including those time elements separately. It would be good to keep for backward compatibility, but yes we should probably define where the temporal search is applied.

**Comment by doublebyte1** [comment]
I think there was a discussion to use "created" and "updated" referring to the time the record was created, in order to align it with stac: https://github.com/opengeospatial/ogcapi-records/issues/178

**Comment by pvretano** [comment]
This issue is resolved by PR #179. 
The PR renames _recordCreated_ and _recordUpdated_ to _created_ and _updated_  to align with STAC and removes _created_ and _updated_ from Table 10.  The _created_ and _updated_ fields from Table 10 (which refer to the resource) are moved into the **link** structure.

**Comment by pvretano** [comment]
28-NOV-2022: Agreed to merge PR #179.  @tomkralidis can then review and close this issue.

**Comment by pvretano** [comment]
12-DEC-2022: Closing with @tomkralidis concent.
