### ISSUE TITLE
Local Resource Catalog filtering and "queryables" endpoint

### ISSUE THREAD

**Issue by ycespb** [opengeospatial/ogcapi-records#196]
The current document gives the "/collections" endpoint as an example of a "Local Resources Catalogue".  The document also explains that "filtering" can be applied to any "Local Resources Catalogue" (https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalogue_cql2-filter).  What is not fully clear is the endpoint that should/could be used to advertise the queryables for such a "Local Resources Catalogue".  For the example of the "/collections" endpoint, would "/queryables" be the endpoint (with rel="queryables" in the landing page) to advertise the queryables applicable to the "/collections" endpoint  to support "collection search" ?  This is the assumption also used in the Testbed-18 Engineering Report OGC 22-018.  It would be really helpful to have some guidance in the standard for this issue.

**Comment by pvretano** [comment]
09-JAN-2023: @pvretano agrees that this is an issue and will look into it.

**Comment by ycespb** [comment]
A possible approach may be to advertise the location of the Queryables object that can be used for collection search via a rel="../queryables" link in the (JSON) response of the /collections resource, which would be similar to the discovery of an OSDD in an OpenSearch (Atom) response as defined in https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#autodiscovery-in-rssatom (which uses rel="search" instead).
