### ISSUE TITLE
Possible 2023 code sprints ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#198]
An issue to capture plans for code sprints in 2023.  OGC has type 2 code sprints that can be organized by SWGS.  All that needs to be done is to sumbit an event request with the following information ...

The Event Request would provide the following information:
• Name of the event
• Date(s) of the event, comma separated in YYYY-MM-DD format
• Start and end times for each date of the event
• Point of contact for the event (likely the SWG Event Organizer)
• Location (‘City/Town, Country’ if hybrid event or ‘Virtual’ if virtual-only)
• Scope of the events (standards covered)
• Link to a Google Doc or GitHub wiki page that presents the announcement of the event

scheduled, please submit an email to [developers@ogc.org](mailto:developers@ogc.org) with the subject heading: Request for Type 2 OGC Code Sprint.

Code Sprint plan is at https://portal.ogc.org/files/?artifact_id=103032

**Comment by pvretano** [comment]
@m-mohr nothing yet but I think we should plan for something in the Fall ... Sept. perhaps.

**Comment by ghobona** [comment]
We are planning to hold a Type 1 Code Sprint in October. Exact dates are yet to be confirmed. Type 1 means that all OGC working groups will be invited to participate. The Sprint Plan for 2023 is available [here](https://portal.ogc.org/files/?artifact_id=103032).

**Comment by pvretano** [comment]
15-MAY-2023:  So, SWG agrees that a code sprint in the Fall is what we want.  Still trying to decide whether we do our own dedicated one in early Sept., join the OGC code sprint in Oct. or do both.  The idea with the "both" scenario is that we start code sprint work in Sept. and then (if necessary) continue on in the Oct. code sprint.

**Comment by m-mohr** [comment]
There will also be a STAC sprint in September and we could potentially co-host...

**Comment by pvretano** [comment]
16-OCT-2023 SWG MEETING:  Task for the upcoming code sprint

1. @kalxas @tomkralidis want to work on the ATS.
2. @tomkralidis work on federated search extension.
3. @cportele will be working on AsyncAPI for Features which would also be transferable to Records.
4. @pvretano work on Crawlable and Local Resources catalogues to validate specification

With regard to the next SWG meeting, the feeling is to cancel the scheduled SWG meeting in 2 weeks and simply let the participants at the Code Sprint meet on a flexible schedule to discuss issues ... which will be records in this repo.

**Comment by tomkralidis** [comment]
As well, @fgravin will be attending (remote + day 3 in person) to help out on [facets](https://github.com/opengeospatial/ogcapi-records/issues/52).

**Comment by tomkralidis** [comment]
@pvretano should we close given #321?
