### ISSUE TITLE
Is temporal geometry a valid expression to use?

### ISSUE THREAD

**Issue by kalxas** [opengeospatial/ogcapi-records#205]
https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/requirements/records-api/REQ_query-param-datetime-response.adoc

https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/requirements/local-resources-catalogue/REQ_param-datetime-response.adoc

**Comment by pvretano** [comment]
That is the term that OGC API Features uses so I used it too ...

**Comment by cnreediii** [comment]
My only issue - and I believe I have mentioned this before - is that when one searches for "temporal geometry", the searcher gets: https://soundcloud.com/temporalgeometry. Temporal Geometry is a manufacturer of royalty-free sample libraries with a focus on innovative and musical sound design. A deeper search find PyTorch uses geometric temporal. If one then searches for "temporal geometry" definition, first hit is OGC moving features. A bit later there is a CSIRO definition of temporal geometry that is different from OGC moving features. 

Checking OGC API - Features, yes temporal geometry is used but never explicitly defined. Finally, in the DGGS Abstract Spec we find: Temporal geometry is geometry constrained to one of the temporal coordinate systems, defined by TemporalCS in [ISO 19111:2019](https://docs.ogc.org/as/20-040r3/20-040r3.html#ISO19111-2019). Temporal geometry primitives instant and interval implement the temporal analogues of point and line respectively in [ISO 19107:2019](https://docs.ogc.org/as/20-040r3/20-040r3.html#ISO19107-2019).

My point is that the OGC needs to have a very explicit agreed to definition for temporal geometry that is used across all OGC standards. Seems to me that the DGGS definition is well stated and clear as to its provenance. Features should be updated to use the same definition as DGGS.

Just sayin' :-)
