### ISSUE TITLE
Add reference in class_jsonfg requirement

### ISSUE THREAD

**Issue by kalxas** [opengeospatial/ogcapi-records#206]
https://github.com/opengeospatial/ogcapi-records/blame/master/core/standard/requirements/requirements_class_jsonfg.adoc#L9

**Comment by pvretano** [comment]
@kalxas since we decided a while back that jsonfg is not currently useful to Records, can we close this issue?

**Comment by kalxas** [comment]
@pvretano shall we remove that line above then?

**Comment by pvretano** [comment]
Closing. Resolved by #210 which removes the JSON-FG conformance class as per SWG decision made in issue #176.

**Comment by kalxas** [comment]
Thank you
