### ISSUE TITLE
clarify conformance link relation

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#214]
For responses containg a link to `/conformance`, clarify whether to use a shortname (`conformance`, per below example), a URI or a CURIE.

```json
{
"rel": "conformance",
"type": "application/json",
"title": "Conformance",
"href": "https://demo.pygeoapi.io/master/conformance"
}
```

**Comment by pvretano** [comment]
According to the [Features](https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_link_relations) specification the rel is `conformance`.  I think we should just track what Features does in this respect.  @tomkralidis if you are satisfied with this then please close this issue.
