### ISSUE TITLE
Add the concept of the STAC Catalog to the crawlable catalogue clause

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#222]
STAC has STAC Items, STAC Catalog and STAC Collection.  OGC API Records only describes Collections (i.e. catalogues) and Items (i.e. record).  However, if you are trying to describe a static or crawlable catalogue that contains a hierarchy that may not be possible without the idea of a "STAC Catalog".  This issue is created to explore this requirement a bit further.

**Comment by pvretano** [comment]
So, we need to add an additional structure, lets call it Directory or Folder or Node, that is basically just a file with links.  We should probably just use the schema from STAC ... https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/catalog-spec.md.  I'll create a PR for this but in the mean time, if anyone has additional comments add there here.

**Comment by cnreediii** [comment]
Directory and folder are basically synonymous. However, the use of node would be problematic. The formal definition for a node (ISO/OGC) is: 0-dimensional topological primitive. The node concept is fundamental to topologically structured vector data. I would therefore go with directory or folder.

**Comment by mhogeweg** [comment]
there are many other definitions for 'node'. think networking, not spatial primitives in this case. Apart from that I"m not sure what the point here is. does OGC Records not have the concept of a 'catalog'? only 'collection' and 'item'?

**Comment by cnreediii** [comment]
@mhogeweg Sure (networking datasets typically uses topological structures so same usage of the node concept) I should have added that the most common use of node in OGC/ISO standards is for the topology case (primary) and in leaf hierarchies (secondary) such as used in I3S and 3D Tiles. I just want avoid any confusion in OGC terminology.

**Comment by pvretano** [comment]
21-APR-2023: @pvretano and @kalxas prefer the name `folder`.

**Comment by pvretano** [comment]
30-OCT-2023:  PR #260 was rejected and instead OARec uses the record collection object to also build hierarchies so we can close this issue.
