### ISSUE TITLE
Providers: Isn't the first schema just a link?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#227]
When writing https://github.com/opengeospatial/ogcapi-records/issues/178#issuecomment-1505797658 I realized that the "first" schema (i.e. url and roles) is basically a weak variant of a link.

It is a URL with roles. This basically is the same as a href and a rel in a link, BUT it has the weakness that 
1. url != href
2. no `type` is specified

So the example usecase with the vcard (VCF) means a client can't properly detect what kind of file it actually loads. If the client would know upfront whether it is a VCF, it could actually do something useful with it.

Thus, I'm wondering whather the "first" schema should actually be removed and instead be a link with a "author" (or some kind of OGC URI such as `http://www.opengis.net/def/curie/ogc/1.0/rel/contacts`) rel type?

Context with regards to STAC: In STAC the `url` is meant to point to a webpage that contains browsable information, not necessarily a machine-readable format as implied by OAR. The intentions seem somewhat different so I don't think they necessarily need to align.

**Comment by pvretano** [comment]
@m-mohr I've removed the first schema from party.yaml altogether since it is not really necessary.  The larger schema only has `name` as mandatory so you can make it as slim or fat as you like including only the bits of contact information desired.  This was implemented in PR #230.

**Comment by kalxas** [comment]
I think this should be closed, the PRs are merged.

**Comment by m-mohr** [comment]
Indeed.
