### ISSUE TITLE
Make sure that the templated links and the required rels in links in records is consistent with Features ....

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#234]
See: https://github.com/opengeospatial/ogcapi-features/pull/812 and https://github.com/opengeospatial/ogcapi-features/pull/819

**Comment by pvretano** [comment]
01-MAY-2023:  The main points of this issue are to (a) make sure that https is used where appropriate (e.g. examples) and (b) add a requirements/recommendation that basically says that `prev` or `previous` are fine since they are synonyms of each other and more generally that `rel` values with synonyms also in the IANA registry are OK.

**Comment by m-mohr** [comment]
> and more generally that `rel` values with synonyms also in the IANA registry are OK.

I don't like this. This opens a rabbit hole of potential synonyms and then people implement what others may not expect. You also newer know what IANA may add in the future.

Is chapter a synonym of (sub)section? Is start a synonym of first? Is up equivalent to parent? Is describedby a synonym for describes? Is index = contents? ...

**Comment by pvretano** [comment]
@m-mohr I'm only referring to link relations that IANA specifically says are synonyms ... which is the case with `prev` and `previous`.  As far as I know, the other pairs of link relations that you mention are not specifically indicated in the IANA link registry as being synonyms for each other.  I haven't checked (but I will) but I don't think there are that many cases where IANA specifically mentions that two link relations are synonyms of each other.

**Comment by m-mohr** [comment]
Ah, thanks for the clarification. So "prev" and "previous" and "icon" and "apple-touch-icon" only. I'm still not sure this needs to be mentioned at all, except explicitly for prev and previous (as it is right now, I think).
