### ISSUE TITLE
Contacts: Role suggestions

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#242]
> Update from OARec discussion at the [Open Standards and Open Source Software Code Sprint](https://github.com/opengeospatial/developer-events/wiki/Open-Standards-and-Open-Source-Software-Code-Sprint).
> 
> - add an annex for contact role code examples (similar to the annex on resource types).  This can provide suggestions for communities looking for guidance, while not constraining those who already have these in place.

_Originally posted by @tomkralidis in https://github.com/opengeospatial/ogcapi-records/issues/228#issuecomment-1523431458_
            

Issue #228 was closed due to the PR, but it seems the last comment is still open. So moving to a new issue.

**Comment by tomkralidis** [comment]
Thanks @m-mohr.  Fixed in #240, if you have time/can take a look just the same, that would be great.

Hope you are feeling better!

**Comment by m-mohr** [comment]
Ah, I did not see #240. Thanks.
