### ISSUE TITLE
Remove hoursOfService in contacts

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#245]
Based on a discussion in #230:

> I feel like hoursOfService is so niche, that I'd actually remove it as it can also be encoded in the free-text field `contactInstructions` as it is describes as "[...] instructions on [...] when to contact the responsible party."

_Originally posted by @m-mohr in https://github.com/opengeospatial/ogcapi-records/pull/230#discussion_r1181100401_

**Comment by pvretano** [comment]
@m-mohr @tomkralidis I changed hours of service to respond to @m-mohr about a string being too free form.  I'm personally ok with (1) leaving it as a sting, (2) leaving the current structure, (3) removing it altogether.  If @m-mohr and @tomkralidis  can come to a consensus I would be happy to implement your decision.  If anyone else want to chime in too, now it the time.

Apologies for the "fast" merges.  My available time to work on Records is going to be limited soon so I want to push this as much as possible to get to a version that we can hand off to the OAB for review.

**Comment by m-mohr** [comment]
Thanks @pvretano. In the STAC extension I removed it already ;-) So whatever Records does, the extension doesn't care as additional properties are handled without issues. @tomkralidis Which option do you prefer?

**Comment by tomkralidis** [comment]
Let's keep an optional `hoursOfService` as a string.  This property is resident in both ISO and DCAT, and in use by data providers when providing contact information.
