### ISSUE TITLE
ISO code for country?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#261]
I'm implementing the contacts field right now and the country field in the address would be much more helpful (e.g. for address formatting) if it was just an [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166) (alpha-2?) code instead of a free-form text.

I'm wondering whether we should:
- require it?
- recommend it?
- just mention it?
- ignore it? ;-)

**Comment by tomkralidis** [comment]
fwiw, WMO WIS2 standards put forth ISO 3166 alpha-3.

**Comment by m-mohr** [comment]
Not sure about alpha-2 vs 3, I just used alpha-2 because it sometimes used for address generation (e.g. "DE-33607 Bielefeld").

**Comment by pvretano** [comment]
06-JUL-2023: Will add recommendation to specification to use [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166) ... most likely to use alpha-3 since there are a couple of implementations that use that.

**Comment by tomkralidis** [comment]
PR in #297
