### ISSUE TITLE
schema validation issues

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#263]
As part of automated WMO Core Metadata Profile (WCMP2) validation, we are implementing a schema which extends the Records model per https://github.com/wmo-im/wcmp2/blob/3aabc432ae2d66fd408a54475ef41a286058717a/schemas/wcmpRecordGeoJSON.yaml

We create a bundled schema of the resulting record schema using [Stoplight Studio](https://stoplight.io/studio).  Steps can be found at https://github.com/wmo-im/wcmp2/blob/main/schemas/README.md (note: if anyone is aware of existing Python tooling that can automate conversion from YAML to JSON [including reference resolving] I'll gladly switch).

We then use [check-jsonschema](https://pypi.org/project/check-jsonschema) to perform validation of instance documents against the bundle as part of CI workflow.

`check-jsonschema` is reporting the following errors with the schema proper:
- https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml#LL26C15-L26C19
  - changing from `type: null` to `type: "null"` fixes the error
- https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/contact.yaml#L52
  - changing from `"pattern": "^+[1-9]{1}[0-9]{3,14}$"` to `"^\\+[1-9]{1}[0-9]{3,14}$"`, but I'm not sure if this is expected per se.  It is critical that we provide a few examples for this property.  Can someone provide?
- https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/contact.yaml#L47 and https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/contact.yaml#L62
  - these should be arrays

PR to fix is in #262, but I'd like some feedback on the impact of these changes related to other tooling.

cc @pvretano @kalxas @m-mohr

**Comment by m-mohr** [comment]
> * changing from `"pattern": "^+[1-9]{1}[0-9]{3,14}$"` to `"^\\+[1-9]{1}[0-9]{3,14}$"`, but I'm not sure if this is expected per se.  It is critical that we provide a few examples for this property.  Can someone provide?

This is expected. It just fixes a regexp from invalid to valid. 

Here is an example:
+492518398765 (49 Germany, 251 Münster, 8398765 local phone number)

**Comment by tomkralidis** [comment]
Is this a relevant example then?  I can add to PR but just wanted to make sure :)

**Comment by tomkralidis** [comment]
Thanks.  I wanted to ensure it's random so that someone is not receiving years of phone calls because of the specification :)

**Comment by m-mohr** [comment]
Not sure, 83 is the prefix of University of Münster. I haven't checked whether 98765 is used. But the issue always exists. A phone number that is "random" and "unused" right now may be used tomorrow.

**Comment by m-mohr** [comment]
Hah, I found some example phone numbers: https://softwareengineering.stackexchange.com/questions/376535/whats-the-phone-number-equivalent-of-example-org

So you can use:
- +441134960000 (UK)
- +12065550199 (US)

**Comment by tomkralidis** [comment]
Updated to `+14165550142`
