### ISSUE TITLE
contactPoint?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#268]
I still see some mentions of contactPoint in the source:
https://github.com/search?q=repo%3Aopengeospatial%2Fogcapi-records%20contactPoint&type=code

Is this intentional? Wasn't this replaced by contacts?

**Comment by pvretano** [comment]
This is a reference to Part 2 not Part 1.  Part 2 was split out a very long time ago and has not been updated in ages.  It is full of kruft that will need to be removes once editing of Part 2 resumes.

**Comment by pvretano** [comment]
Closing since Part 2 is not even half baked yet and when it is cleaned up many things will change including this reference.
