### ISSUE TITLE
null time schema issue?

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#272]
_Originally posted by @tomkralidis in https://github.com/opengeospatial/ogcapi-records/issues/266#issuecomment-1562734183_

There seems to be an issue when trying to validate `recordGeoJSON.yaml` using some schema tools (in my case `check-jsonschema`.
 
@m-mohr @pvretano @kalxas I've put forth [this gist](https://gist.github.com/tomkralidis/cc674035706640d93a1f9527f18cb91a) for review/comment.  Note that I am using the schema in a non-OpenAPI context here in support of record validation.

**Comment by m-mohr** [comment]
nullable in JSON Schema is not defined. You need to add "null" as a type. 

In OpenAPI you need to use nullable and can't use "null" as a type.

Unfortunate conflict in the two specs...

**Comment by tomkralidis** [comment]
Thanks @m-mohr.  So downstream applications using `recordGeoJSON.yaml` as a schema in a non-OpenAPI context will hit this issue and can workaround depending on their schema workflow (example: https://github.com/wmo-im/wcmp2/blob/main/schemas/wcmpRecordGeoJSON.yaml#L21) ?

**Comment by m-mohr** [comment]
Yes
