### ISSUE TITLE
Distinguishing links to STAC / OGC API - Records?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#276]
Do we need a way to distinguish links to STAC and OGC API - Records somehow?

A link to a STAC JSON file with relation type child looks exactly like a link to OGC API - Records, although they are not fully compatible. They both would look as follows:

```
{
  "href": "./catalog.json",
  "rel": "child",
  "type": "application/json"
}
```

I could see a world where STAC and Record JSON files will be mixed in one catalog (actually, I'm currently working on a project that would benefit from it).

The only way I could distinguish them right now consistently, is probably to load the files and check whether `stac_version` is present (STAC) or not (=> likely Records, but could also be something else).

Thoughts?

**Comment by pvretano** [comment]
@m-mohr that did not occur to me but now that you mention it, it might be a good idea.  I was thinking of defining specific MIME types for each of the OARec file types ...

- application/ogc-record+json for an OARec record
- application/ogc-folder+json for an OARec folder
- application/ogc-catalogue+json for an OARec record collection (aka catalogue)

I think that would help the link issue ... no?

**Comment by m-mohr** [comment]
Yes, that would be a good solution, indeed.

**Comment by pvretano** [comment]
@m-mohr OK ... I'll create a PR to add these MIME types

**Comment by pvretano** [comment]
@m-mohr yeah, I realized that about the record media type last night when I was thinking about this some more.  `application/geo+json; application=ogc-record` sound find to me.
