### ISSUE TITLE
How to handle empty parameters?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#281]
In req. 18 I find the following definition for the q parameter:

> If an empty q operator is passed (i.e. q=), the server SHOULD ignore this operator as if it was not specified by the client.

Is this general behavior to be applied to the parameters? It is not explicitly mentioned for externalId and type, thus it is confusing whether the same behavior as for q should be applied. This seems also undefined for the parameters inherited from Features (datetime, bbox, limit).

So either mention it for all parameters (which implies changes to Features), or just add a general note that if a parameter is empty (and nothing else is specified explicitly for individual parameters) it should be ignored.

**Comment by pvretano** [comment]
Oh please!  Keep the spam coming @m-mohr!  We need eyes on the specification to fix all it inconsitencies which we sometimes don't see because we are in the thick of it.  Rather I should say, THANK YOU, for taking the time to review and comment! :)
