### ISSUE TITLE
Presentation page: the swagger link is broken

### ISSUE THREAD

**Issue by fgravin** [opengeospatial/ogcapi-records#298]
From the OGC API Records presentation page: https://ogcapi.ogc.org/records/

The [link](https://dev.api.weather.gc.ca/msc-wis-dcpc/openapi#) for the swagger exemple is broken.

**Comment by pvretano** [comment]
10-JUL-2023: @pvretano with talk with OGC and resolve the issue.

**Comment by tomkralidis** [comment]
PR in https://github.com/opengeospatial/ogcapi-org/pull/41

**Comment by tomkralidis** [comment]
Fixed.
