### ISSUE TITLE
Contacts: Subdivision?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#299]
For a company as contact that has a subdivision, how can I express that?

Example:

Organization: Example Corp, Inc.
Subdividion: Accounting Dept.

Beforehand I used the positionName, but after #296 I'm not sure whether that's still intended?

**Comment by tomkralidis** [comment]
What I have seen in the past is profiles using a convention (organization=Government of Canada; Environment and Climate Change Canada).  Having said this, given organizations have various structures/hierarchies and meanings behind them (one organization's subdivision could be another organization's branch, for example).  For me, it sounds like this could be a custom element and not in core.

**Comment by pvretano** [comment]
21-AUG-2023:  The sentiment of the SWG is to leave the core as it is.  Anyone, of course, can add additional member to the schema (such as subdivision) to suit their requirements.

**Comment by pvretano** [comment]
26-SEP-2023: Not further action on this issue ... closing.
