### ISSUE TITLE
Implementations.md

### ISSUE THREAD

**Issue by cdharbin** [opengeospatial/ogcapi-records#307]
I was going to test with the implementations and noticed that the first items link, https://eratosthenes.pvretano.com/cubewerx/cubeserv/default/ogcapi/catalogues/collections/sentinel1cat/items?f=json, throws an error,
"CWWRS: A server-side exception has occurredCWWRS: failed to connect to database, raised in CwWrs_HandleOgcApiEndpoint() in file "wrsModule.c" line 732 (process 2564062)CWWRS: failed to establish DML connection to database, raised in wrsDbs_Connect() in file "wrsDbs.c" line 251 (process 2564062)CWWRS: ORA-01017: invalid username/password; logon denied, raised in cwdbsConnect() in file "cwdbs.pc" line 126 (process 2564062)"

Could someone check that the implementations are working and remove/comment out if not accessible?

**Comment by pvretano** [comment]
Oops... I decommissioned eratosthenes a while back!  Try atlas instead ...

https://atlas.pvretano.com/cubewerx/cubeserv/default/ogcapi/catalogues/collections/sentinel1cat/items?f=json

I'll update my implementation page listings shortly.

**Comment by cdharbin** [comment]
Thanks!

**Comment by pvretano** [comment]
@cdharbin I think I've updated all the links now ... give it a shot, let me know if you run into any issues.

**Comment by cdharbin** [comment]
It was working great and then it started timing out.

**Comment by pvretano** [comment]
Yeah, this is my dev machine and I has to shutdown and startup the database a few times today.  Are you getting the timeout now?

**Comment by cdharbin** [comment]
Yes. It looks like it is still timing out. I can't reach the site now.

**Comment by cdharbin** [comment]
Will the site be back up tomorrow? Or should I try again next week?

**Comment by pvretano** [comment]
@cdharbin the site is up now and I am able to access but I can't figure out why your access is timing out ... still looking into it.

**Comment by pvretano** [comment]
@cdharbin can you try again ... looks like it was a firewall issue.

**Comment by cdharbin** [comment]
Thank you so much. It is working!

**Comment by pvretano** [comment]
Closing for now.  Reopen if you run into further issues.
