### ISSUE TITLE
Example record - language literal does not match schema object type

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/ogcapi-records#308]
https://github.com/opengeospatial/ogcapi-records/blob/master/core/examples/json/record.json#L53

"language": "en",

https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml#L75 

 $ref: language.yaml

which declares type:object

and fails schema validation.

**Comment by pvretano** [comment]
SWG meeting 11-DEC-2023: @pvretano will coordinate with @tomkralidis to get these examples updated.
