### ISSUE TITLE
Cubewerx implementation is throwing errors

### ISSUE THREAD

**Issue by cdharbin** [opengeospatial/ogcapi-records#315]
I was testing the items endpoint, https://atlas.pvretano.com/cubewerx/cubeserv/default/ogcapi/catalogues/collections/sentinel1cat/items?f=json&limit=100,  from the implementation page and it's not working anymore.

**Comment by pvretano** [comment]
Should be working now.  Forgot to startup the database on my server.

**Comment by cdharbin** [comment]
Thanks!
