### ISSUE TITLE
Issues with implementation links 

### ISSUE THREAD

**Issue by cdharbin** [opengeospatial/ogcapi-records#317]
I was trying to test some of the implementations listed and found some issues with the sites:

https://demo.ldproxy.net/geoinfodok returns 404
https://gpt.geocloud.com/ogcrecords/collections/master/items doesn't return expected OGC API Records format.
https://gpt.geocloud.com/ogcrecords/collections/master/items/456688037ef0400fa46c87a3bec3a893 throws error

**Comment by cportele** [comment]
I created #318 for the first link.

**Comment by cdharbin** [comment]
Thanks

**Comment by pvretano** [comment]
SWG meeting 11-DEC-2023: Will wait until the next SWG meeting to see if anyone updated the geocloud link.  If not, we will remove them from the implementation page and close this issue.
