### ISSUE TITLE
possible 2024 code sprints

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#321]
There is discussion for a virtual type 2 code sprint for OGC API - Records, GeoDCAT SWG and MetaCat DWG for Q2/Q3.  We need to gauge our interest and goals for such an event.

Adding this issue here for discussion at our next SWG meeting.

**Comment by tomkralidis** [comment]
FYI a code sprint is being planned for 10-12 July 2024 at Geovation in London, UK.

**Comment by rob-metalinkage** [comment]
The GeoDCAT development methodology will be supported by the process of mapping metadata standards including ogc api records and STAC extensions to existing DCAT and other well scoped vocabularies, and adding missing spatio-temporal concepts into the GeoDCAT namespace.  Testing these mappings can be automated, so a code sprint could co-develop code and test cases for a range of profiles of Records, and the test cases added to the profiles expressed as OGC Building Blocks. The mappings themselves will be a combination of JSON-Ld contexts and transformations. Transformations may be in many forms, and could be implemented in code libraries.

**Comment by PeterParslow** [comment]
@ByronCinNZ : are we still expecting a "MetaCat" / GeoDCAT code sprint (or similar) in November 2024? Could this also be of interest to API Records?

**Comment by ghobona** [comment]
The 2024 OGC Metadata Code Sprint has been announced. The event will take place 18 to 19 November 2024.

The Metadata Code Sprint will have a primary focus on the following group of tools, APIs and encodings:

- OGC GeoDCAT
- OGC API – Records
- ISO 19115 JSON encodings
- STAC 

Register to participate in person or remotely at https://www.ogc.org/ogc-events/the-november-2024-ogc-metadata-code-sprint/
