### ISSUE TITLE
OAB Prep

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#344]
- [x] 1. Review the ATS to make sure that all requirements are covered (Angelo, Tom)
- [x] 2. Validate all JSON examples (Peter)
- [x] 3. Send email to @cnreediii  to request a review (Peter)
- [x] 4. Apply @cnreediii  review comments (Peter)
- [x] 5. Prepare motion in SWG for submission to OAB and RFC.

**Comment by tomkralidis** [comment]
Thanks @kalxas for rounding out the ATS.  Some comments on the ATS:

## Abstract Tests 4, 22, 28, 35, 36
We should point to a concrete URL as opposed to a GitHub (working) schema?
  - chicken and egg problem, schema to be published first
  - note that AT35 "predicts" the authoritative schema URL
## Abstract Tests 51, 54, 
YAML schema is shown inline, this should be a reference to a URL

I've put forth a PR in #346 to fix the above.

**Comment by kalxas** [comment]
Thanks @tomkralidis 
The PR looks good for me.

**Comment by pvretano** [comment]
Since we are presenting to the OAB 14-MAY-2024 we have thus prepared for the OAB so we can now close this issue.
