### ISSUE TITLE
Empty ids parameter.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#347]
Say I an querying by ids ... `/collections/{catalogId}/items?ids=...`.  If the ids parameter is specified BUT is empty how should the catalogue respond?  Should it:

1. Ignore the parameter?
2. Should it returns an empty result set?

**Comment by cportele** [comment]
As the parameter is an array, an empty parameter value is an empty array and thus the response should be an empty result set.

**Comment by pvretano** [comment]
18-MAR-2024 SWG Meeting:  Concensus seems to be that the server should respond with an empty response collection.  @pvretano will make the necessary updates to the specification.
