### ISSUE TITLE
incompatibility with STAC - time property

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/ogcapi-records#349]
records makes `time` required,  

using the OGC building block register tooling for testing STAC is a valid extension [1]  identifies that all STAC examples fail when tested against record schema.

see https://ogcincubator.github.io/bblocks-stac/build/tests/report.html

either Records or STAC needs to change, and it appears Records would be easiest.  ( a profile of records with mandatory "time" may be a solution if there is a requirement.)

[1]  https://ogcincubator.github.io/bblocks-stac/

PS:  BBlocks for Features and Records is in progress to test all examples in the base specs.

**Comment by m-mohr** [comment]
See also https://github.com/opengeospatial/ogc-feat-geo-json/issues/69

**Comment by rob-metalinkage** [comment]
can be closed by https://github.com/opengeospatial/ogcapi-records/pull/353
