### ISSUE TITLE
STAC incompatibility: id format uri overrestrictive  

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/ogcapi-records#365]
suggest relax to string to support compatibility with STAC expectations of Features 

(note also strings can be interpreted as URI using JSON-LD contexts : see https://opengeospatial.github.io/bblocks/register/bblock/ogc.ogc-utils.iri-or-curie

https://raw.githubusercontent.com/opengeospatial/ogcapi-records/master/core/openapi/schemas/recordGeoJSON.yaml

```  id:
    type: string
    description:
      A unique identifier of the catalog record.
    format: uri
```

STAC example:
https://github.com/stac-extensions/eo/blob/3e5c9239a74276feaf49efa5274c252e977f9ebc/examples/item.json#L7

```
 "id": "20201211_223832_CS2",
```

**Comment by m-mohr** [comment]
Oh, that's something that slipped through in the STAC / Records crosswalk:
https://github.com/stac-utils/stac-crosswalks/tree/master/ogcapi-records

I think relaxing to string-only would be appreciated.

**Comment by kalxas** [comment]
good catch, +1 to relax

**Comment by pvretano** [comment]
@m-mohr @kalxas it shall be done ...

**Comment by rob-metalinkage** [comment]
Thanks folks.  Any volunteers to set up testing for the rest of the STAC extensions suite - 
https://github.com/ogcincubator/bblocks-stac/tree/master/_sources/extensions.

Happy to set up a coaching/doctors surgery session to help with the process - its fairly simple just for this Use Case - even if the machinery under the hood is doing some work to deal with JSON Schema version compatibility issues.  Gives a pathway to automatically maintain registers of STAC extensions as well as linking them to each other and other related standards.

You could also integrate this into the STAC extensions template so each extension gets tested as part of development.

https://github.com/opengeospatial/bblock-template

(Create an issue on the template if there is a blocker for doing this)
