### ISSUE TITLE
itemType

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-records#375]
Requirement `/req/record-collection/itemType` states:

> If a catalog references both records and other catalogs then, its itemType property SHALL be an array of strings whose elements enumerate the types of resources referenced by this catalog (i.e. record and catalog).

This will break clients implementing Features, because the value of the "itemType" member is a string, not an array of strings. If a client receives an array, this will likely result in errors, because the value is unexpected.

**Comment by pvretano** [comment]
Updated the requirement [/req/records-api/record-collection-response](https://github.com/opengeospatial/ogcapi-records/pull/376/files#diff-133e3fdd9e5924f50ca1bf19e8f44622e64ade77f073e3b461246718552ffd0d) in the records API requirements class to make it clear that in the records API case (which uses Features) that `itemType` is a string and its values is fixed to `record`.  This also required some schema changes here and there to enforce this.
