### ISSUE TITLE
`q` and order-independent AND?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-records#379]
[Requirement 22](https://docs.ogc.org/DRAFTS/20-004.html#core-query-parameters-q) says:

> C   Search terms that may appear together (logical OR) in a record SHALL be separated by literal commas.
> D   Search terms that must appear together, and **in the order specified**, in a record SHALL be separated by one or more white space characters.

It seems to me that a common use case is to search for multiple things that must all appear in the records, but you don't care in what order they appear. So I am quite surprised to see this _in the order specified_ in req 22 part D.

How would such a use case be handled? I want to search for all collections where both `canada` and `weather` appear, but I don't care if the title/description says "Weather in Canada" or "Canada Weather".

I would have expected that `/collections?q=weather canada` would match both.

It is also somewhat ambiguous whether it matters whether there is anything in between the multiple terms.
(EDIT: from reading the notes below the requirements, it seems that only spaces can be there)

Would that match "Weather of Canada", but not "Canada weather"?
Or only if "weather canada" appears without any words in between?

When searching in keywords, must all terms appear together in the same keyword, or can they be terms in separate keywords (in which case, does this really depend on the order in which keywords are defined?).

Perhaps defining `/collections?q=weather+canada` would support this ubiquitous AND use case, while still supporting searching for a consecutive sequence of term as per Req 22 D.

Thanks!

**Comment by cportele** [comment]
@jerstlouis 
`/collections?q=weather,canada` matches both "Weather in Canada" and "Canada Weather". 

`q` is a query parameter with `"style": "form", "explode": false` and a string array of keywords as the value. That means the keywords are separated by a comma. If you write "weather canada" then this is a single keyword and the text must appear in one of the properties as written (except for the case).

**Comment by jerstlouis** [comment]
@cportele But `/collections?q=weather,canada` will also match "weather in Hawaii" and "Middle-Earth Style Map of Canada", since it's an OR, right?

**Comment by cportele** [comment]
Correct

**Comment by jerstlouis** [comment]
@cportele For me as a user, that makes this `q` parameter mostly useless.

The only thing is you would hope the server sorts more relevant results (results matching all terms) first, but if the client is paging through all results anyways, this is preventing from reducing the result set to only meaningful results, and causes lots of unnecessary strain on the server and wastes bandwidth.

Hence this issue, though I realize it is probably too late :( I just realized that `q` cannot handle AND...

**Comment by cportele** [comment]
@jerstlouis 

There are use cases for both interpretations of `q=weather canada` (the current one and your preference). Selecting one over the other makes `q` more useful for some searches and less for others. It was an explicit decision to keep `q` simple and not introduce a new micro-format for each value in the `q`array.

See https://github.com/opengeospatial/ogcapi-records/issues/295.

**Comment by jerstlouis** [comment]
Thanks @cportele for pointing me to the issue where this was discussed.

I still _really_ think we need a way to do an order independent AND search, without the considerably more more difficult to write CQL2 filter option.

What would be a recommended way for an implementation to extend this in a non-breaking way?

A different parameter (not `q`)? A micro syntax with `+`? A separate parameter changing the interpretation of space separators?

**Comment by pvretano** [comment]
19-AUG-2024 SWG meeting: The SWG disccused this at length before and concluded that the very simple keywork-search capability was what is desired in part 1.  If you want to enhance the capability then another parameter with different semantics would need to be defined.
