### ISSUE TITLE
recordsArrayName and records

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-records#404]
Sorry, I just saw this yesterday. Don't really want to delay Records standardization, but it seems this snuck in after requesting RFC comments (including mine), so I'd like to raise my concerns about the two properties even after RFC review.

While I think it could be valuable to inline items, I think this should not be part of core and instead be in a separate part.

1. "records" is part of the schema, but "recordsArrayName" allows to rename it, which is something not seen for any other property and feels liek feature-creep. It is also not clear from the specification why this is renamable.
  1. Why does it need a way to rename that property?
  2. If it's allowed to rename it, why is a fixed name specified in the records schema (i.e. `records`)? It means if you change the `recordsArrayName` you'll loose validation from schemas in OpenAPI etc.
2. The specification is not clear on the usecase. If I understand it correctly, people can add thousands of records into a collection and return it in the GET /collections response. That makes it unmanageable and should be forbidden or be discouraged at least.
3. Generally, the descriptions about `records` and `recordsArrayName` are pretty minimal and should be extended.

Generally, the usecase seems rather niche so I think it's better suited in a separate part (or at least conformance class). This is additional behaviour that shouldn't be in the core. Keep things small and simple. This adds complexity that is not needed for most of the usecases in my opinion.

Side note: We had similar behaviour in STAC, but we deprecated it as it didn't work overly well. Instead we just reuse existing structures like the ItemCollection. Yes, that needs to file to be transferred (Collection and ItemCollection) sometimes, but it's cleaner and doesn't need special handling or a special structure. https://github.com/stac-extensions/single-file-stac/tree/main

**Comment by pvretano** [comment]
@m-mohr this was a change that resulted from an RFC comment from @jerstlouis.

As I explained at our last meeting the name of the array that holds inline "records" can be different in the local resources catalog case.  If the local resources catalog is at the `/collections` endpoint then the name of the record array is "collections".  If the local resources catalog is at the `/processes` endpoint then the name of the record array is "processes"  So there needs to be a way to let a catalog client know what the name of the record array is.  The default value is "records".

It is unfortunate that I could not get you and @jerstlouis on the same call to battle it out but at this point I think what's done is not.  I will try to add some more clarifying text to the specification to better explain the role of these members.
