### ISSUE TITLE
What would the mechanism be to map a metadata model to standard model?

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/ogcapi-records#41]
I see in the editors draft Draft Outline for OGC API - Catalogue, that a catalogue may implement any underlying data model that it wants (e.g. ebRIM, ISO19115/ISO19119, etc.) however, all internal data models must be mapped to the record schema defined in this standard.

It may be too early to ask, but what would the mechanism be to map a metadata profile to the standard model?

**Comment by pvretano** [comment]
@nmtoken That would be up to the implementor or the community that controls the underlying data model to define how it is mapped into the core queryables.

**Comment by nmtoken** [comment]
@pvretano probably a badly phrased question; I meant the mechanism of  doing the mapping, do we create a JSON schema, YAML, something else? I have no feeling for how that would be done.  I didn't mean how do we as a community agree how to map our community standard.

**Comment by pvretano** [comment]
24-AUG-2020: We are not sure what the question is asking but we believe that the the question is about what the standard will provide with regard to defining the standard metadata model.  We are planning to provide a JSON-Schema and YAML descriptions of the standard core record.

**Comment by pvretano** [comment]
SWG MEETING 08-FEB-2021: Closing as schemas are provided in the repo.
