### ISSUE TITLE
Metadata crosswalk between OGC standards

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/ogcapi-records#44]
Attached is a spreadsheet of a crosswalk between the proposed OGC API Records queryables and CDB 1.2, 2D TMS, and the 2D Tiling Abstract Spec. A few quick observations:

1. The Records API "extent" queryable includes both space and time. DCT, CDB, and so on have this as two separate metadata elements. This is shown in the spreadsheet.
2. I am not sure what is meant by "type".
3. CDB has a critical requirement for explicit metadata on language. How is this being handled in the Records API. Are you relying on Common? 

That's all more now.
[Metadata Queryables crosswalk.xlsx](https://github.com/opengeospatial/ogcapi-records/files/4913504/Metadata.Queryables.crosswalk.xlsx)

**Comment by pvretano** [comment]
@cnreediii Language is negotiated as per HTTP (i.e. via the Accept-Language header).

**Comment by cnreediii** [comment]
Hmm. Content-Language is the language of the page you're serving. Accept-Language is a list of languages you PREFER to accept. ... The Content-Language entity header is used to describe the language(s) intended for the audience, so that it allows a user to differentiate according to the users' own preferred language. So, seems to me that the API needs to "know" (and the user may wish to know) what the content language is in order to be effective and useful. Or am I missing something - like the back-end server is supposed to worry about language.

**Comment by rob-metalinkage** [comment]
there are also discussions about potential content-negotiation by CRS  - the general pattern is:

server has some capabilities exposed by variable facets, covering a range of possible values of those facets.
clients have a set of capabilities and channeled user preferences across these facets.

somehow the client needs to know what it can ask for, how to ask, and what are allowable ranges

negotiation is one option - compare lists to see the intersection
"getcapabilities" style self-description is the other option.

ideally these co-exist,

**Comment by nmtoken** [comment]
For language negotiation with HTTP, I assume that means language of the metadata record?   (which is conditional for ISO 19115 ~ You must supply the metadata language if it is not defined by the document encoding.)

What seems to be missing is language of the described resource, which is mandatory for ISO 19115

**Comment by pvretano** [comment]
Two points, one about general discovery of API capabilities and another about language ...

I've always favoured the use of the OPTIONS method for API discovery (i.e. what formats are supported, what languages are supported, what methods are supports, what CRSs are supported, etc.).  However, OPTIONS is not used much in the Web at large; in other words that is not a usual interaction pattern at so every time I have raised the issues of using it, the response has been lukewarm. 
 
With regard to language, I see @nmtoken point and so I have created issue #45 to revisit the discussion about language.  Again, the prevailing philosophy is that specification defines a bare minimum of record properties BUT a catalogue can choose (either by self-decision or because of some community-developed standards) to extend that set of properties and include whatever else is needed/wanted.  The point is that we may discuss it in the SWG and still decide that it should be left out; but, I will raise the issue once again!

**Comment by cnreediii** [comment]
@nmtoken - Yes, I was thinking of the language used in the resource. Thanks

**Comment by pvretano** [comment]
24-AUG-2020:  Had a discussion with regards to dates.  Two type of dates were identified.  Dates associated with the resource being described by the catalogue and dates associated with the actual catalogue records itself.  It is believed the the queryables "modified" and "extent (temporal)" are sufficient for capturing the dates associated with the resource being described.  We need to add dates associated with the records itself; created and modified should be sufficient. @pvretano will look at adding the records dates and present at the next meeting.

**Comment by uvoges** [comment]
![Collecion-MD-Dates](https://user-images.githubusercontent.com/12135911/91126430-3d8e9180-e6a4-11ea-922d-48cf4d78301a.JPG)
![EO-Product-MD-Dates](https://user-images.githubusercontent.com/12135911/91126435-40898200-e6a4-11ea-952f-3d1e69c73560.JPG)
Here two slides where we (OpenSearch-EO SWG) tried to model the most important dates (for the EO context).
The first shows dates relevant to collection metadata, the second the dates relevant for product metadata (and meta-metadata).
You can find the elements used for search, response and the mapping to the underlying metadata model (ISO19115-2 for collection metadata and EOP metadata (OGC 10-157r4) for EO product metadata)

**Comment by ghobona** [comment]
This was discussed in the OpenSearch Geo. The OpenSearch work looked collection and products metadata. This is captured in OGC 13-026r9. Uwe.

I hope there will not any limitations on the number of dates and times in the record. **Need clarification on this**. Chris.

Will the Core support different metadata specifications or is the expectation to allow future profiles? Gobe

The SWG is going to provide a JSON Schema for a minimal record. Angelos.

Trying to have something in the standard that says that that is what the record holds, would not be appropriate. Alex.

**Comment by pvretano** [comment]
As @kalxas mentioned, the record schema defines the minimal record but there is a permission in the specification that says any number of additional properties can be added to the record and that includes additional date and time properties.

**Comment by pvretano** [comment]
03-MAY-2021:  The record schema in the draft has now settled and there ability to add additional properties by communities of interest is always available so we are closing this for now.
