### ISSUE TITLE
Text Search Conformance Class

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#5]
As per https://github.com/opengeospatial/CAT4.0/blob/master/core/outline.adoc#text-search-conformance-class :

- should we rename to 'Full Text Search Conformance Class'
- should this conformance class be bumped into OGC API - Common? There's some similar questions on the OGC API - Features side as well

**Comment by uvoges** [comment]
It would be good for us - to be able to derive an "API-Records/EO" (e.g. referencing some CC and adding only CCs for EO specific things) from OpenSearch-EO - when either API-Common or API-Records cover our requirements on full text search which are specified in chapter 7.2.4 of https://portal.opengeospatial.org/files/?artifact_id=73994.

**Comment by cportele** [comment]
Meeting 2020-02-24: 
* Full text will be an extension to "Simple CQL". But it should be in the core of OGC API Records.
* We need to see what the specific requirements are (e.g. with respect to linguistic variations, etc., or is a simple LIKE-based approach ok, too), we need to look at typical backends.

**Comment by pvretano** [comment]
Some resources to consider ...

- https://www.postgresql.org/docs/9.5/textsearch-intro.html
- https://docs.oracle.com/en/database/oracle/oracle-database/20/ccref/
- https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html
- https://docs.microsoft.com/en-us/sql/relational-databases/search/full-text-search?view=sql-server-ver15
- https://www.ibm.com/support/knowledgecenter/es/SSEPGG_10.1.0/com.ibm.db2.luw.admin.ts.doc/doc/c0057450.html
- https://code.tutsplus.com/tutorials/full-text-search-in-mongodb--cms-24835
- https://docs.couchbase.com/server/6.5/fts/full-text-intro.html

**Comment by tomkralidis** [comment]
Thanks for the analysis Peter. Also:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/full-text-queries.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
- https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html#the-standard-query-parser

+1 for an agnostic approach.  Perhaps we can provide (in landing page, queryables or some other endpoint) the ability to (optionally) point to documentation about the semantics for those who want to know more

**Comment by tomkralidis** [comment]
Meeting 2020-05-04

- added `q` parameter schema
- add conformance class/description to document

**Comment by pvretano** [comment]
Closing as requirements have been added to the draft for the q parameter.
