### ISSUE TITLE
Add reference back to root to sub pages

### ISSUE THREAD

**Issue by mhogeweg** [opengeospatial/ogcapi-records#57]
As I'm working on implementing OGC Records, I found it handy to include a reference back to the landing page in for example the conformance or collections pages. I suggest this to be included in the spec as at least an option.

See http://geoss.esri.com/ogcrecords/conformance

**Comment by jvanulde** [comment]
@mhogeweg is `parent` a valid relation? I haven't seen it before but I could be mistaken. Perhaps we can use the `up` relation? Agree that the reference back to the landing page is convenient.

**Comment by mhogeweg** [comment]
parent is used as relation type for example in a [STAC item](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#link-object) along with self, root, collection, derived_from, and alternate. If the collection intended there is analogous to the collection in OGC API, that would also be a relationship type to include.

**Comment by cportele** [comment]
`parent` is not a registered link relation type, but `up` is.

In Features there was an issue/discussion about this some time ago. See https://github.com/opengeospatial/ogcapi-features/issues/181. The consensus was that implementations are free to add such links, but we did not see a good reason to require them.

**Comment by mhogeweg** [comment]
Fair point, but neither are `collections` or `conformance` and those are already identified in the spec here. I see `collection` is  a type and `profile` is defined as "Identifying that a resource representation conforms to a certain profile, without affecting the non-profile semantics of the resource representation." Should collections and conformance then also be reconsidered?

**Comment by cportele** [comment]
> Should collections and conformance then also be reconsidered?

Features has specified `items`, `data` and `conformance` as new link relation types (not `collections`), because we did not find one that is registered. Since these are generic terms, IANA will not register them (at least unless they are defined in an IETF or W3C standard). Going forward, all unregistered link relation types in OGC API standards will be URIs, managed by the OGC Naming Authority. There was a recent TC vote on this after some discussion in Common and the OGC NA.

**Comment by pvretano** [comment]
19-OCT-2020: This was discussed in features and it was determined that this is not essential information for many use cases (i.e. being at a leaf and jumping all the way back to the landing page) although we don't prevent people from including those links if they want to do so.

**Comment by mhogeweg** [comment]
As long as a future compliance test indeed 'allows' those additional convenience links, that's good.
