### ISSUE TITLE
common queryables?

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/ogcapi-records#58]
Is this group going to define Common Queryables like in http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#table_1 ?

This would help us a lot in STAC as we add fields at the 'collection' level, and I think would help everyone making collections, to know additional JSON fields that they can add, that don't have to be mapped. Perhaps it's a 'building block' that stands alone. But to me that's far, far more valuable for interoperability than an API that I can put 'any catalog model' into.

**Comment by pvretano** [comment]
@cholmes first, I believe that the SWG understands and acknowledges the importance of the "extend the /collections endpoint to be queryable as a catalogue" use case.   Currently there is a conformance class named "Collections" in the specification just to emphasize that point.  Furthermore, I am personally working (because I have come to agree with you about the importance of this use case) to write that conformance class/extension and have it ready along with the rest of the specification around the end of this month.  If the SWG decided to keep it in the code, then great, I will move the text into the core.  If not, no problem, the extension text will be ready.  However, minimizing the use cases that others see as important too does not help the process.

Second, the current **but not yet final list** of core queryables is here: https://htmlpreview.github.io/?https://github.com/opengeospatial/ogcapi-records/blob/master/20-004.html#_response_6.  Let me know if you see anything else that we should add (or take away).

Finally, see issue #43.  Disregard the "extension" tag since we are still discussing its status the SWG although (and I don't want to put words in anyone's mouth here) I believe the sentiment in the SWG is make it an extension.

**Comment by cholmes** [comment]
Ah sweet, this is great progress. And I didn't mean to minimize the other use cases, just to state what's important to me. Apologies if it came off that way.

That's really great there's a list of queryables now. The particular ones we're struggling with right now are the time ones. Particularly times of the resource vs records (in the semantics of records). Your approach is interesting, if I understand it:

* `created` when the metadata was created
* `changed` updated whenever the metadata has a change (so likely would start with the same time as created)
* `modified` when the data has been changed. Presumably when the data is created modified would be the creation date?

What's the reasoning for not having a created equivalent for the data? 

In STAC we currently use just 'created' and 'updated', but they are really at our 'feature' level. We're realizing we need a created/updated at the collection level, which would make good sense to align to records. And then we also have an echo of it in our features, since each STAC Item is itself metadata, and refers to 1 or more 'assets' (resources) that can each have different update times.

**Comment by pvretano** [comment]
@cholmes, hmm, I think that might be a side effect of the fact that the core queryables were partially derived from the core queryables of CSW 3.0 and the date the data was created was not listed there.

The issues is captured here now and the SWG will review it at the next SWG meeting.

**Comment by m-mohr** [comment]
I must admit "changed" and "modified" is a bit confusing to me as it's not clear from their names what they refer to. Just by reading the names I'd assume they do the same thing as the words are basically synonyms.
Also I'm wondering whether Records could adopt `updated` so that we don't need a breaking change in STAC again?

**Comment by uvoges** [comment]
The names are derived from ISO19115 or former Catalogue Specs.

dateStamp/modified for metadata of the resource (see CSW 2.0, MD_Metadata in ISO)
created/published/revised for the data (asset) (see CI_Citation in ISO)

For metadata mostly only the last revision date (dateStamp/modified) is interesting (e.g. in the context of harvesting use cases)

But the names have often led to confusion.

Maybe?:
- metadataModified
- dataCreated
- dataPublished
- dataModified

**Comment by uvoges** [comment]
@pvretano are these really queryables: [https://htmlpreview.github.io/?https://github.com/opengeospatial/ogcapi-records/blob/master/20-004.html#_response_6](url) (maybe I missed a discussion)
How do I use "links" and "associations" in a GET-request ?

**Comment by pvretano** [comment]
@uvoges I believe they are.  Actually @cportele has proposed (see issue #28) a mechanism to query associations and links.

**Comment by pvretano** [comment]
@m-mohr I agree.  In the text I am going to call them record-created, record-modified, created and modified.  The 'record-' version apply to the catalogue record.  The non 'record-' version apply to the resource being described by the record.  In the GeoJSON encoding they will look like this and you can tell from the context which is which:
```
{
   "id": "...",
   "type": "Feature",
   "geometry": { ... },
   "created": "2020-11-01",    <--- record creation date
   "modified" "2020-11-10",   <--- last modification date for record
   "extent": {...},
   "properties": {
      "externalId": "...",
      "title": "My Coverage",
      "description": "My coverage showing NO2 concentrations over Canada",
      "keywords": ["tag1", "tag2", "tag3", ... "tagN"],
      "type": "coverage",
      "created": "2019-04-20",      <--- date resource was created
      "modified": "2019-07-30",    <--- last date the resource was modified
      "publisher": "http://www.someserver.com/vcards/0ef5gy7ejd",
      "themes": [{"category": "node1","taxonomy": "http:///www.someserver.com/taxonomies/d8fhnt40d"}, ...],
      "formats": ["image/geotiff","application/x-netcdf"],
      "contactpoint": "http://www.someserver.com/vcards/9jtr75vb",
      "license": "https://creativecommons.org/licenses/by/4.0/legalcode",
   },
   "links": [ "http://...","http://...",...],
   "associations": ["http://....","http://...",...]
}
```
Better?  Also, I am not opposed to changed "modified" to "updated".  I will raise that with the SWG.

**Comment by m-mohr** [comment]
Indeed, we also use the same terms for both metadata and data and it should be clear from the location what they refer to.
Unfortunately, this conflicts. We have data related timestamps in assets, while the metadata related timestamps are in properties (and you have data there, that's the conflict). We don't have any timestamps at the top-level. Hmm... how do we resolve this conflict? @cholmes

**Comment by pvretano** [comment]
@m-mohr when you say "assets" you mean in the assets section of a STAC record.  Correct?

**Comment by m-mohr** [comment]
Yes, here's an example:

```json
{
    "stac_version": "1.0.0-beta.2",
    "stac_extensions": [
      "timestamps"
    ],
    "id": "LC08_L1TP_107018_20181001",
    "type": "Feature",
    "bbox": [
        148.13933,
        59.51584,
        152.52758,
        60.63437
    ],
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    152.52758,
                    60.63437
                ],
                [
                    149.1755,
                    61.19016
                ],
                [
                    148.13933,
                    59.51584
                ],
                [
                    151.33786,
                    58.97792
                ],
                [
                    152.52758,
                    60.63437
                ]
            ]
        ]
    },
    "properties": {
        "datetime": "2018-10-01T01:08:32Z",
        "created": "2018-10-02T00:00:03Z",
        "updated": "2020-05-20T12:13:02Z",
        "published": "2018-10-03T06:45:55Z",
        "expires": "2025-01-01T00:00:00Z",
        "platform": "landsat-8",
        "instruments": ["oli", "tirs"],
        "constellation": "landsat"
    },
    "assets": {
        "blue": {
            "href": "https://landsat-pds.s3.amazonaws.com/c1/L8/107/018/LC08_L1TP_107018_20181001_20181001_01_RT/LC08_L1TP_107018_20181001_20181001_01_RT_B2.TIF",
            "type": "image/tiff; application=geotiff",
            "title": "Band 2 (blue)",
            "created": "2018-10-02T00:00:00Z"
        },
        "green": {
            "href": "https://landsat-pds.s3.amazonaws.com/c1/L8/107/018/LC08_L1TP_107018_20181001_20181001_01_RT/LC08_L1TP_107018_20181001_20181001_01_RT_B3.TIF",
            "type": "image/tiff; application=geotiff",
            "title": "Band 3 (green)",
            "created": "2018-10-02T00:00:00Z"
        },
        "red": {
            "href": "https://landsat-pds.s3.amazonaws.com/c1/L8/107/018/LC08_L1TP_107018_20181001_20181001_01_RT/LC08_L1TP_107018_20181001_20181001_01_RT_B4.TIF",
            "type": "image/tiff; application=geotiff",
            "title": "Band 4 (red)",
            "created": "2018-10-02T00:00:00Z"
        },
        "thumbnail": {
            "href": "https://landsat-pds.s3.amazonaws.com/c1/L8/107/018/LC08_L1TP_107018_20181001_20181001_01_RT/LC08_L1TP_107018_20181001_20181001_01_RT_thumb_large.jpg",
            "title": "Thumbnail image",
            "type": "image/jpeg",
            "created": "2018-10-02T00:00:01Z"
        },
        "index": {
            "href": "https://landsat-pds.s3.amazonaws.com/c1/L8/107/018/LC08_L1TP_107018_20181001_20181001_01_RT/index.html",
            "type": "text/html",
            "title": "HTML index page",
            "created": "2018-10-02T00:00:02Z",
            "updated": "2020-05-20T12:13:01Z"
        }
    },
    "links": []
}
```

**Comment by m-mohr** [comment]
Documentation: https://github.com/radiantearth/stac-spec/tree/master/extensions/timestamps

**Comment by pvretano** [comment]
@m-mohr so the create/updated dates in the properties section represent the creation and last update date for this GeoJSON object?   Sorry for all the question just want to make sure I understand clearly! ;)

**Comment by m-mohr** [comment]
Yes, correct. I guess STAC should improve the documentation on timestamps ;-)

**Comment by pvretano** [comment]
@m-mohr thanks!  I see the problem now.  In the original encoding I had all the time stamps in the properties section and they were named  record-created, record-modified, created, modified.  Where the 'record-' where equivalent to STAC created/updated in the properties section and create/modified were equivalent to the create/updated in the assets section.  I suppose we could do the following for records to align better with STAC:
1. All timestamps go into the properties section.
2. create/modified refer to the creation/modification date of the record (what you call metadata) at is the same as the STAC created/updated in the properties section.
3. resource-created and resource-modified refer to the creation/modification dates of the resource (what you call data).
Does that sound like a reasonable compromise?  If yes, I will raise this with the SWG.
Keep in mind, I will also raise the issue of renaming 'modified' to 'updated'.

**Comment by m-mohr** [comment]
@pvretano Sounds good to me, thanks! What do you think, @cholmes?

Maybe some more background on our timestamps in assets: We are using the data related timestamps at the asset level as the individual files in the assets may have different timestamps. I'm not exactly sure how you point to "data" in records (links?), but would that also be a use case for you? Then you could put it in links(?)...

Another thing I'm wondering about: Isn't this something that should be specified at the level of API Commons? It feels like this is something that could also be valuable for other APIs. And in this case, I'm wondering whether resource is the best term/prefix?

**Comment by pvretano** [comment]
@m-mohr API common building blocks usually start life in one of the SWGs and then move up to common once general usability has been determined.  I can see that a "timestamps" building block could eventually move up to common but we probably need to flash it out a bit more here between records and STAC including implementations that support it.
As for pointing to data, that is one of the purposes of the associations section where you can include download or access links to the resource being described by the record.

**Comment by m-mohr** [comment]
Okay, so associations is basically for Records what assets are for STAC. Can they also include timestamps? (Not necessarily proposing to do it, just wondering whether it could be useful?)

**Comment by pvretano** [comment]
@m-mohr they seen to serve similar functions but the associations section is an array of links with rel's in records while the assets section is an object is STAC.   Is the set of keys is the assets section derived from some controlled vocabulary?

**Comment by m-mohr** [comment]
@pvretano It's pretty much the same, it's just a different data structure. There's (in most cases) no vocabulary for the keys. The keys have the purpose do describe the assets in collections (some kind of a schema for assets, see https://github.com/radiantearth/stac-spec/tree/master/extensions/item-assets), but that better works with objects. Otherwise we could likely also adopt arrays.

**Comment by mhogeweg** [comment]
I'm sure it is clear to all, but to me the distinction between 'applies to the record' and 'applies to the resource' is not clear. The geometry and type are properties of the resource, but appears in the record part above. I can see an identifier, an owner (who owns the registration of the resource in the catalog), when it was registered/updated there, what collection(s) it is part of in this catalog, what is its review/approval status in the catalog as 'record'. Properties that are extracted from the metadata in my view are all resource properties.

**Comment by cholmes** [comment]
Apologies for the slow response on this. I missed notifications, then wrote a response yesterday, but it seems like I didn't hit 'comment' and now it's gone.

But yes, +1 to created/modified (or updated) and resource-created / resource-modified. There is actually a place for the resource- ones in STAC, as a property level roll-up of the asset level created/updated times, which will be useful since it gets searched. So we'd likely make use of those. And then we'd likely use all of them at the 'collection' level.

And yes, updated would be great for further alignment. Technically we could keep ours and use 'modified' at 'collection' level, but aligning would be nice. 

When is the next SWG group? I'd like to try to make it for this discussion.

**Comment by pvretano** [comment]
@cholmes this Monday.  Details on the portal.

**Comment by pvretano** [comment]
16-NOV-2020: We decided to rename "modified" to "updated" and include, in the specification, a crosswalk to other metadata standards like ISO19115:2003 and DCAT.

**Comment by m-mohr** [comment]
Coming back to common queryables and the discussion today: Isn't having no common queryables an interoperability issue? Like if we have datetime in properties, then people could add it as for example "datetime", "properties.datetimes" or "temporal" to queryables. This makes developing tools that work on multiple servers hard as you need to figure out from queryables what is actually referring to the datetime in properties. If you have at least a recommendation how to map queryables, that would probably at least help. But even better would probably be to have a strict mapping rule as we have in STAC (i.e. properties.datetime). Optinions?

**Comment by pvretano** [comment]
03-MAY-2021:  We do have "core" queryables (see Table 12) defined that set the core queryable names.  In table 12 we do list the corresponding GeoJSON key but the name of the queryable is not the GeoJSON key but the named listed in table 12.  Perhaps we need to add some more text to the specification to clarify that?  I will do it (@pvretano).

**Comment by pvretano** [comment]
09-AUG-2021:  As mentioned in the last comment, an additional column has been added to tables 11 & 12 mapping the core queryables to their corresponding GeoJSON key/tag names.  We can close this issue.
