### ISSUE TITLE
(meta) Only republish draft documents on change

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-records#72]
Instead of pushing the HTML and PDF versions each day, only push on change.

**Comment by pvretano** [comment]
I made changes.  I am only pushing so that I a fresh copy for the SWG meeting tomorrow.  Not sure what the status is of OGC's nightly builds of the HTML and PDF files.  Seems to be set up but I will follow up with them after tomorrow's meeting to make sure it's all working correctly.

**Comment by bradh** [comment]
e50df57f37a82924e0b8fd821e1eb66d1ba9a5e3 actually  deleted the files, but if you look at the commit history you'll see a daily change, even when the content is the same.

**Comment by pvretano** [comment]
Yeah, I noticed that ... so yes, I don't have to check in the HTML and PDF.  OGC's process will rebuild nightly.

**Comment by pvretano** [comment]
2021-JAN-25: Clemens pointed out that the actual issue @bradh is highlighting is that the HTML and PDF document get generated in the **REPO** each night even when no changes have have made.  Actions: (1) Remove HTML and PDF from repo and only reference the version that get auto-generated each night at docs.ogc.org.  (2) Update all READMEs, etc. to link to the versions in docs.ogc.org.

**Comment by pvretano** [comment]
Removed all HTML and PDF documents checked into the REPO and updated all README files to reference the nightly generated version of the draft available here: http://docs.ogc.org/DRAFTS/20-004.html

**Comment by bradh** [comment]
Followup at https://github.com/opengeospatial/ogcapi-records/pull/73
