### ISSUE TITLE
break out CQL as dedicated standard

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#8]
cc @cportele

[CSW 2.0.2](http://portal.opengeospatial.org/files/?artifact_id=20555) has a chapter on CQL as a generic grammar for querying.

Assess, investigate and refactor/update into a common query grammar as part of OGC API efforts.

**Comment by cportele** [comment]
Some context: The following recommendation is from the OGC Testbed-14 Next Generation APIs Complex Feature Handling Engineering Report:

> [**Make CQL an OGC standard on its own**](http://docs.opengeospatial.org/per/18-021.html#rec-1b)
> 
> If CQL would be supported by a WFS extension as a result of the recommendation 1 above, it should be extracted from the Catalogue Service standard and become a standard on its own.
> 
> The CQL standard should provide a clear and unambiguous specification of the query language and requirements for implementations. It also clarify how CQL provides API building blocks that can be reused by WFS 3.0 or other NextGen standards.

The following is from another recommendation (note that this is the context of feature queries but applies to record queries, too): 

> One conformance class should support CQL queries on dataset and collection resources as outlined [here](http://docs.opengeospatial.org/per/18-021.html#cql). The CQL should be restricted to the profile that is implemented in GeoTools and other libraries (e.g. no support for compound attributes, relationships, attributes with multiple values).

**Comment by cportele** [comment]
SWG Meeting 16-DEC-2019: The Features API SWG is working on this as ["Part 3"](https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql) (might be moved to become a part of OGC API Common once it appears).

**Comment by cportele** [comment]
We expect that CQL will eventually be moved to Common and we will be able to reference it. We can close this issue.
