### ISSUE TITLE
itemType property on collections should be mandatory

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-records#87]
Both OGC API - Features and OGC API - Records use the `/items/` URI segment itemType property.

To ensure that client applications and compliance tests can distinguish between the two APIs, the itemType property will need to be mandatory in OGC API - Records.

For background, please see the comment by @cportele at https://github.com/opengeospatial/ets-ogcapi-features10/issues/134#issuecomment-768943254

**Comment by cportele** [comment]
The property cannot be mandatory, because it isn't mandatory in Features/Common. However, it is already stated that the Records-related requirements only apply to collections with item type `record`. See http://docs.opengeospatial.org/DRAFTS/20-004.html#req_core_rc-op, part B.

**Comment by pvretano** [comment]
22-FEB-2021: Records already has a requirement that says that everything in the specification only applies to collections where itemType=records.  In other words, itemType is mandatory for records.
