### ISSUE TITLE
Re-consider all queryables that are links ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#99]
@cportele mentioned that there are several queryables (license, publisher, etc.) that are links that could, in fact, be included as associations in the associations sections with the appropriate rel.  It is a bit of a grey area but we should revisit these and see if this is something we might want to consider to make the core ever more lean.

**Comment by pvretano** [comment]
08-MAR-2021: @cportele will look at the IANA registry to see if there are additional rels besides license that might be used in this way (i.e. to move these properties from 1st order properties to links in the associations or links section).  We are not saying we are going to do this right now; we are just investigating.  Also, with relation to issue #103 we might consider making all properties that are URIs (such as publisher, contactpoint, license, etc.) either be URIs or embedded objects (without a specific schema).  This, however might put an additional implementation burden so more feedback is required.

**Comment by pvretano** [comment]
22-MAR-2021:  We need to have a discussion about whether moving a property like licence from the properties section to an association link reduces is queryables.  Or more generally what the impact of moving properties to links is and what the rules are about deciding if a property should be a property in the properties section or a link.

**Comment by pvgenuchten** [comment]
An aspect here is in case of a scenario where a json response is annotated as json-ld by adding a json-ld context.
A ld-context links to direct properties of a class. Having multiple elements sharing a key (identified by an attribute) is not optimal. In general, programming against explicit properties is nicer than programming against a list of elements, and identify relevant ones by a attribute property.

Although I understand the benefit of reusing the <link rel="license"/> to generic atom/html clients.

**Comment by m-mohr** [comment]
URLs are not well queryable anyway: There are so many different URLs for e.g. Apache 2.0 that you can't figute out what to search for or you get incomplete results. For querying you need a common list of licenses like SPDX, although that has not a lot for "data". But anyway, links in general should be in links (or associations) and if that's hard to query, we should find a way to make it possible, I guess?

**Comment by mhogeweg** [comment]
Agree on that. would it be more useful to query on the role/purpose of the link? the link is to a license or to a service or to a homepage or...

**Comment by cportele** [comment]
> @cportele will look at the IANA registry to see if there are additional rels besides license that might be used

Here is what I found:

* queryable "type" (a URI): There is also a link relation type "type" defined as "Refers to a resource identifying the abstract semantic type of which the link's context is considered to be an instance."
* queryable "license" (a URI): The link relation type "license" is defined as "Refers to a license associated with this context." 
* queryable "rights" (a string): There is a link relation type "copyright" that is defined as "Refers to a copyright statement that applies to the link's context." However, that is from HTML 4 and HTML 5 treats "copyright" as an alias of "license", so we probably should not use "copyright". In addition, often there won't be a URI to link to and a rights value will be provided as text. 

On the other aspects discussed in this issue: In general, "license" or "type" could be queryables and still be encoded as links in a representation. That said, I agree it would be better for filtering, if the license and type queryables are not URIs, but strings. To support queries, the server should list the values in the queryables resource. Maybe recommend the use of SPDX for the license values. 

Where a URI exists for the license or the type, this can be added as a link in the record response, too.

**Comment by pvretano** [comment]
28-JUN-2021: So the basic proposal is that the type and license fields in the record properties be strings of codes with enumerated values listed in the API description rather than URIs.  The codes should be limited in length to something like 64 chars.  The URI values for the type and license fields would be links in the links section if the URIs are available.
The idea is that the type and license values in the properties section could be convenient values for filtering and the links to longer text values (for licence for example) or pointing to type definitions in a registry would live in the links section. 
One thing to consider in the specification is the ability to handle multiple licenses.  STAC uses "various" as a special value in addition to SPDX to the string license in the properties section.
@cportele will create a PR to implement this.
